### ISSUE TITLE
Optional mask

### ISSUE THREAD

**Issue by zefexdeveloper** [beholdr/maska#1]
Is it possible to create an optional mask like: `#.## cm` where the user can write: `1.32cm` or `1.3cm`? And also for a more complex one. I want to make it so the user can type `67.300 kg` or `67kg` and the variations for kg.

**Comment by beholdr** [comment]
You could use something like this:

    <input v-maska="{ mask: 'D* cm', tokens: { 'D': { pattern: /[.0-9]/ }}}">

[Example](https://jsfiddle.net/yxvpezt4/)

**Comment by zefexdeveloper** [comment]
That is not quite what I wanted. This regex is allowing any character, I want to keep the format `#.## cm` but the last `#` is optional, something like `#.##?` (for example)

**Comment by beholdr** [comment]
Currently it's not possible, but I'll see if I could implement optional flag.

**Comment by zefexdeveloper** [comment]
That would be great, thank you. I saw a few libraries that has an array implementation like this: `['##', '###']` others with a flag such as `##[#]` where `[#]` is optional, and so on.

**Comment by beholdr** [comment]
I’ve added dynamic mask feature using array for mask. Please see updated demo and docs.
