### ISSUE TITLE
Uncaught SyntaxError: Unexpected token 'export' (at maska.js:149:1)

### ISSUE THREAD

**Issue by lcichanowicz** [beholdr/maska#100]
Hi.  My project got approval for Maska 1.5 a little while back, so I cannot use 2.0.  When I try to use 1.5 via CDN, I get a browser console error:

![image](https://user-images.githubusercontent.com/4871064/206205964-66c9c0a6-7203-44b7-bc53-2f3df979db60.png)

I found a StackOverflow post (not specific to Maska) saying to add type="module", but I don't think that applies here.  I did try it.

`<script type="module" src="https://cdn.jsdelivr.net/npm/maska@latest/dist/maska.js"></script>`

That does make the Unexpected token 'export' error go away, but I then get this error.

![image](https://user-images.githubusercontent.com/4871064/206205851-84ae1ff8-75e8-4f0a-a4c7-a3531ccfcff1.png)

Please advise.

**Comment by LuizAlmeida777** [comment]
Same here

**Comment by beholdr** [comment]
Use concrete version in URL `https://cdn.jsdelivr.net/npm/maska@1.5.1/dist/maska.js`

**Comment by lcichanowicz** [comment]
Thanks, @LuizAlmeida777 and @beholdr.  Before I saw your fix, I tried making a local copy of raw latest (from here on GitHub) from dist, and that works fine.  I like your solution better, though.  Can you please explain what the issue is with using "@latest" in the script src?

**Comment by LuizAlmeida777** [comment]
I'm using on the head:
```<script src="https://cdn.jsdelivr.net/npm/maska@latest/dist/maska.js"></script>```

But today I realized that the applications broke:
![image](https://user-images.githubusercontent.com/106160143/206225468-0b0639bd-5c2d-4bc2-9c4d-ff40c6498d61.png)

**Comment by LuizAlmeida777** [comment]
I change to 1.5.1, but don't work in input:
![image](https://user-images.githubusercontent.com/106160143/206226382-bdc87a81-623b-434b-a02d-f272507a8900.png)

**Comment by beholdr** [comment]
@LuizAlmeida777 please provide reproduce link

**Comment by LuizAlmeida777** [comment]
Using latest:
https://www.remaza.com.br/simulador-automovel
![image](https://user-images.githubusercontent.com/106160143/206227046-9b271eca-f8eb-464f-b8fe-f6446f6b0b24.png)

Using 1.5.1:
https://desenvolvimento.empresasremaza.com.br/
![image](https://user-images.githubusercontent.com/106160143/206227089-a32f3c1e-023e-4a86-9f3c-cb101bba4f5f.png)

**Comment by beholdr** [comment]
Don't see any errors with 1.5.1 version in console

**Comment by LuizAlmeida777** [comment]
> Don't see any errors with 1.5.1 version in console
yes, but dont work mask on input too

What was the version before the last one modified with "export"

**Comment by beholdr** [comment]
Last v1 version is 1.5.1. It should work as before, no breaking changes.

**Comment by lcichanowicz** [comment]
[@beholdr, does this mean the v1 read-me should be updated to use the concrete version for the CDN instructions?

https://github.com/beholdr/maska/tree/v1#install
