### ISSUE TITLE
v1 README no longer mentions class="masked"

### ISSUE THREAD

**Issue by lcichanowicz** [beholdr/maska#101]
Hi.  I have a plain JavaScript implementation of v1.  Some existing code had a class of "masked" added to input elements using a Maska mask.  The current Maska v1 README does _not_ mention this class.  When I omit the class, v1.5.1 does not mask the field.  There are no errors; but, the masking just does not work.

**Comment by lcichanowicz** [comment]
This article shows the usage of that class.

https://webcodeflow.com/input-mask/

**Comment by beholdr** [comment]
You could use any class. It used for selecting input for masking. Please read the [docs](https://github.com/beholdr/maska/tree/v1#usage-with-vanilla-js).

And please stop creating issues that is not bug. Ask support at Discussions.

**Comment by lcichanowicz** [comment]
Oh, I see how it works now.  I apologize, and I thank you.

**Comment by lcichanowicz** [comment]
> And please stop creating issues that is not bug. Ask support at Discussions.

The first issue I created still seems like a bug.  If someone follows the v1 docs, Maska won't work, right?

**Comment by beholdr** [comment]
I will update docs soon. Thank you.
