### ISSUE TITLE
Mask allow an extra character in Vue

### ISSUE THREAD

**Issue by albertcito** [beholdr/maska#102]
### Describe the bug

Mask allow an extra characters in `vue`

### Steps to reproduce

`data-maska="####"` it should allow max 4 numbers it allow 4 numbers only in the input, but the `ref` element has 5 numbers or a char.

### Reproduction link

Link: https://stackblitz.com/edit/vue3-script-setup-with-vite-5nvdzd?file=src%2FApp.vue

Video: https://user-images.githubusercontent.com/1768483/206267789-9d6a184b-d017-43ee-9bbe-f34e621e9565.mov

**Comment by beholdr** [comment]
That's not a bug. Don't use `v-model` on masked input. Use binding via `v-maska="value"`

**Comment by beholdr** [comment]
Work with v-model should be fixed in v2.1, please check.
