### ISSUE TITLE
Getting error with Vue3 The requested module 'maska' does not provide an export named 'vMaska'

### ISSUE THREAD

**Issue by donnyv** [beholdr/maska#105]
### Describe the bug

Getting error importing vMask
![image](https://user-images.githubusercontent.com/2224189/207389049-c1cd23fa-ded0-4332-86a5-acdd956b4031.png)

### Steps to reproduce

Which steps do we need to take to reproduce the problem?
I am using the CDN with an import map and plain javascript. 
```
<script type="importmap">
        {
          "imports": {
            "vue": "https://mydomain.com/vendors/vuejs-3.2.37/vue-debug.js",
            "maska": "https://cdn.jsdelivr.net/npm/maska@2/dist/maska.umd.js"
          }
        }
</script>
<script>
       import { createApp } from 'vue';
       import { vMaska } from "maska"

const cwPersonInfoForm = createApp({

    directives: { maska: vMaska },
    data(){ ... }
}).mount("#cwPersonInfoForm");
</script>
```

**Comment by donnyv** [comment]
I figured out the problem. Your documentation needs updating. I just found this in another issue.
https://cdn.jsdelivr.net/npm/maska@latest/dist/maska.js
That has the correct export names. 

The CDN you have in the docs doesn't work with Vue3
![image](https://user-images.githubusercontent.com/2224189/207393317-1933e82c-3a8d-4784-88f1-d05c21a57eba.png)

**Comment by beholdr** [comment]
CDN from docs works fine if you use UMD build and prefix all imports with `Maska.` as described in docs.
So you need to use it like this:

``` js
createApp({
  directives: { maska: Maska.vMaska }
}).mount("#app");
```

But you are importing with `<script type="importmap">` so you don't need an UMD build.

**Comment by donnyv** [comment]
Ooooooh, maybe add somewhere about using with importmap. Since importmap is starting to become more popular.

**Comment by minimul** [comment]
This tripped me up too as I'm using importmap or more specifically with https://github.com/rails/importmap-rails.

The fix is to not use the UMD format so in `config/importmap.rb` have this:
```
pin 'maska', to: 'https://cdn.jsdelivr.net/npm/maska@2/dist/maska.js'
```

**Comment by beholdr** [comment]
I have updated docs about ES modules / Import maps using from CDN.
