### ISSUE TITLE
Maska v 2.1.1 not compatible with vue 2 ?

### ISSUE THREAD

**Issue by raphaelnoguier** [beholdr/maska#108]
Hello ! 

I try to update my vue 2 (nuxt 2.15) project from maska 1.5.1 to 2.1.1, but i have this error : 

<img width="1713" alt="Capture d’écran 2022-12-16 à 11 40 27" src="https://user-images.githubusercontent.com/22751073/208080967-b8f32b6b-57fd-482b-ad90-7dd45bda639e.png">

I use it like suggested in the doc : 

<img width="296" alt="Capture d’écran 2022-12-16 à 11 42 48" src="https://user-images.githubusercontent.com/22751073/208081253-ec3b901e-7837-4807-a3dc-4b06283d7392.png">
<img width="170" alt="Capture d’écran 2022-12-16 à 11 43 01" src="https://user-images.githubusercontent.com/22751073/208081256-5953624c-6263-4c95-b694-6de308948f55.png">

Any idea @beholdr ?

Thanks 🙂

**Comment by raphaelnoguier** [comment]
Okay i managed to resolve this issue if this could help someone : 

I had to update my nuxt.config.js build object to : 

```js

build: {
  transpile: ['maska']
 }
 ```
 Resolved by looking at this issue : https://github.com/nuxt/nuxt.js/issues/9223#issuecomment-834832352
 
 Thanks !

**Comment by derHodrig** [comment]
This is also the solution to

```
Module parse failed: Unexpected token (21:129)                                                                                                                                                                                                                                    friendly-errors 14:32:49  
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     } else
|       s.tokens = O;
>     Array.isArray(s.mask) && (s.mask.length > 1 ? s.mask = [...s.mask].sort((e, a) => e.length - a.length) : s.mask = s.mask[0] ?? ""), s.mask === "" && (s.mask = null), this.opts = s;
|   }
|   masked(t) {

```

**Comment by anatolykopyl** [comment]
For anyone still using vue-cli, this is solved by setting 
```javascript
// vue.config.js
module.exports = {
  transpileDependencies: [
    'maska'
  ]
}
```
