### ISSUE TITLE
Directive is not reacting to programmatic changes

### ISSUE THREAD

**Issue by matheustav** [beholdr/maska#114]
### Describe the bug

Hi! First of all, thanks for this amazing tool.

I'm trying to update the text of an input based on my app usage with v-model (or just :value).
Maska works well if the user manually types the value or at 'immediate' update, but not at eventual changes.

### Steps to reproduce

JS:
```
const { vMaska } = Maska

Vue.createApp( {
    directives: { maska: vMaska },
    data() {
        return {
            data: 12,
        }
    },
    mounted() {
        setTimeout( () => this.data = 34, 3000 );
    }
} )
.mount('#app')
```

HTML:
```
<div id="app">
  <input v-maska data-maska="#-#" :value="data" />
</div>
```

In this example the input correctly shows "1-2" initially, but when setTimeout runs (after 3s), the input shows "34" and not "3-4", indicating maska didn't parsed the value the second time.
I also tried to debug by listenning the @maska event and only at the first update it called the listener, confirming the issue with the second setter.

### Reproduction link

https://jsfiddle.net/f4np5gk0/

Thanks!

**Comment by beholdr** [comment]
Thanks! Should be fixed in v2.1.2
