### ISSUE TITLE
Additional check needed before using the `in` operator for CustomEvent.detail

### ISSUE THREAD

**Issue by jsvini** [beholdr/maska#115]
### Describe the bug

Hi, the mask crashes when CustomEvent.detail is a number, the `if` bellow assumes that CustomEvent.detail is always null or an object, but since it's a CustomEvent, it can have anything in the `detail` property.

https://github.com/beholdr/maska/blob/b8a2fe8a8664b940a6208fbb102ebc6671c8ab45/src/mask-input.ts#L93

Need to check if CustomEvent.detail is an object|array before using the `in` operator, or it will crash when it's something else.

### Steps to reproduce

Try to fill this input, it will crash the mask:

https://stackblitz.com/edit/js-maska-3tsemx?file=index.js

**Comment by beholdr** [comment]
Thanks, fixed in v2.1.3
