### ISSUE TITLE
Failed to execute 'setSelectionRange' on 'HTMLInputElement'

### ISSUE THREAD

**Issue by dav245** [beholdr/maska#118]
Using with vue 3. Having globally defined directive and using it on
`<input type="email" v-maska data-maska="####">`
When you delete characters from such input an exception is raised.
While googling i found out same problem can happen with type="number"

Exception in its all glory:
_Uncaught DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('email') does not support selection._

**Comment by cn-2k** [comment]
Same here when `input` is type `number`.

**Comment by dav245** [comment]
One more piece of information from 
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange
method apply only to inputs of types text, search, URL, tel and password

**Comment by beholdr** [comment]
Thanks for investigation.
I don’t know how to properly fix this so I just wrapped `setSelectionRange` in try..catch. It’s minor issue with cursor position for `email` input
