### ISSUE TITLE
v-maska version 2.x.x doesnt work with vuetify v-text-field version 3.x.x

### ISSUE THREAD

**Issue by erudachenko** [beholdr/maska#125]

**Comment by erudachenko** [comment]
`<script setup>
import { vMaska } from "maska"
const body = reactive({
  security_code: ''
})
</script>

<template lang="pug">
v-text-field(v-maska data-maska="####" v-model="body.security_code")
</template>`

**Comment by beholdr** [comment]
Please provide link to reproduce in online sandbox or I will close issue.

**Comment by euheny** [comment]
After simple research:

- script try get dataset.mask from input, but in case of vuetify it stay on component element

```
<input v-maska data-maska="#-#"  />
```
- working


```
<VTextField v-maska data-maska="#-#">
```
- not working (maybe inheritAttrs not binded)

In my case (using TSX) maska perfect working if set config to directive but not in dataset
```
setup() {
  const maskValue = ref('')
  const maskState = reactive({})
  const maskConfig = reactive({ mask: "#-#" })

  return () => <VTextField v-model={maskValue.value} v-mask={[maskState, maskConfig]} />
}
```

Something like this.

**Comment by FernandoRogelin** [comment]
This working for me

https://github.com/beholdr/maska/issues/97#issuecomment-1340614430
