### ISSUE TITLE
Backspace & delete jump cursor to end of input when used on first character

### ISSUE THREAD

**Issue by grouchal** [beholdr/maska#13]
Using either the `DELETE` key or `BACKSPACE` Key to delete the first character in a mask results in the cursor jumping to the end of the input

![maska-first-character-delete](https://user-images.githubusercontent.com/232846/92370501-aa6d4700-f0fa-11ea-9865-aa15df16ff23.gif)

**Comment by beholdr** [comment]
You right, @grouchal. Fixed in 1.1.6. Thanks!

**Comment by ahsathpt** [comment]
this is re-ocurring when using v-model and v-maska directive 2.1.4
