### ISSUE TITLE
data-maska-eager completed boolean early

### ISSUE THREAD

**Issue by jiblett1000** [beholdr/maska#130]
### Describe the bug

I've encountered another bug while using the eager option. Using the same reproduction as my other "eager" bug report, I've encountered a bug where the completed flag is resolving to true one character too early. Take this phone mask for example:

`+1 (###) ###-####`

When using the eager option, the `completed` boolean is resolving to `true` when entering something like `+1 (555) 555-555` rather than `+1 (555) 555-5555`

### Steps to reproduce

The above pretty much sums it up.

### Reproduction link

https://stackblitz.com/edit/nuxt-starter-8swf8v?file=app.vue

**Comment by beholdr** [comment]
Thanks. Should be fixed in v2.1.6
