### ISSUE TITLE
Phone mask prefix issue

### ISSUE THREAD

**Issue by kerim1505k** [beholdr/maska#131]
### Describe the bug

I encountered some strange behavior while trying to use phone mask

For example if there is phone mask on input with attribute "data-mask="+998 (##) ###-####" and you start typing your phone number which starts with 9 then mask prefix is not working correctly. I checked it with different phone prefixes and they all works the same depending on what prefix of phone number you have in data-mask attribute

### Steps to reproduce

I reproduced it on demo page by choosing phone mask example

### Reproduction link

https://user-images.githubusercontent.com/44666463/215722308-d11c18d4-9ad9-4ffd-b219-95be820ddaed.mov

As you see on the video whenever I type "1" the mask prefix is not working as I expected.

**Comment by beholdr** [comment]
It's expected behavior: first `1` is processed as masked prefix. You could use eager-mode if you want to get `+1 1` with the first `1`.

**Comment by STsaruk** [comment]
@beholdr 
I have a very similar situation. According to the pattern, input shouldn't accept characters other than numbers, but if I try to enter something else, the character is cut out, but the suffix appears 

![CleanShot 2023-01-31 at 17 44 14@2x](https://user-images.githubusercontent.com/17137906/215807649-1a7b31c9-274c-4d5f-8137-21be90be306b.png)

**Comment by beholdr** [comment]
@STsaruk did you try without reverse mode?

**Comment by STsaruk** [comment]
> @STsaruk did you try without reverse mode?

yes, but the behavior becomes very strange, I just enter numbers and it starts listing all the cases that are in the dataMask array 

![CleanShot 2023-01-31 at 17 55 29@2x](https://user-images.githubusercontent.com/17137906/215811277-551e89c1-d321-4168-a254-e9dd6eeafcca.png)

**Comment by beholdr** [comment]
As I see on screenshot, it's still `dataMaskaReversed: true`

**Comment by STsaruk** [comment]
> As I see on screenshot, it's still `dataMaskaReversed: true`

sorry, it's just a wrapper component that doesn't reach the input.  Not a very good screenshot, I'll prepare an example in the sandbox now 

![CleanShot 2023-01-31 at 18 02 17@2x](https://user-images.githubusercontent.com/17137906/215813609-50270ee2-a0b6-45b7-b523-8b66a6660d92.png)

**Comment by STsaruk** [comment]
@beholdr example: https://codesandbox.io/s/ant-design-test-forked-vku0vf?file=/src/components/FormTest.vue

**Comment by beholdr** [comment]
Issue with `:data-maska="internetSpeedInputMask"` — `data-maska` property can't accept reactive objects. It should be simple text as in json or, if you need dynamic property, use options reactive object via `v-maska:[options]`.

But you can use multiple token without array mask:

``` html
<a-input
  v-model:value="formState.username"
  v-maska
  data-maska="0 Mbps"
  data-maska-tokens="0:[0-9]:multiple"
/>
```

**Comment by STsaruk** [comment]
The second option [did not work.](https://codesandbox.io/s/ant-design-test-forked-vku0vf?file=/src/components/FormTest.vue) Or maybe I'm using it wrong. 

I'll play with the ` v-maska:[options]`. 

In any case, thank you for your answers

**Comment by kerim1505k** [comment]
I tried to use eager-mode on my input but then I faced new problem. 
I created demo version of it here: https://codesandbox.io/s/interesting-smoke-wrjpys
Whenever I try to type something in my input it fills my input automatically with some random numbers. I really think it's all because of my input listener messing up with this https://github.com/beholdr/maska/blob/master/src/mask-input.ts#L164

**Comment by beholdr** [comment]
@kerim1505k you had two `v-maska` directives on input, I [fixed it](https://codesandbox.io/s/xenodochial-platform-4r7zkw) and it works now

**Comment by kerim1505k** [comment]
Oh god, sorry for that, I didn't notice it. Everything is works perfectly now.
