### ISSUE TITLE
Space after optional caracter

### ISSUE THREAD

**Issue by mrleblanc101** [beholdr/maska#132]
### Describe the bugà
Be this mask
```
options: {
    mask: '1 (###) ###-####',
    tokens: {
        1: { pattern: /[1]/, optional: true },
    },
},
```
If I type `14181231234`, I want `1 (418) 123-1234`
If I type `4181231234`, I want `(418) 123-1234` but I get ` (418) 123-1234`

**Comment by beholdr** [comment]
It’s not a bug, first space in mask is mask symbol too.
I think simplest solution will be to use dynamic function mask, something like this:

``` html
const options = {
  mask: val => val.startsWith('1') ? '1 ### ###-##-##' : '### ###-##-##'
}

<input v-maska:[options]>
```

**Comment by mrleblanc101** [comment]
The plugin seem to have odd behavior:
I also tried this:
```
{
    mask: ['1 (###) ###-####', '(###) ###-####'],
    tokens: {
        1: { pattern: /[1]/ },
    },
}
```
But typing `14181231234` would match the second mask and not the first

**Comment by beholdr** [comment]
Did you tried my solution?

**Comment by mrleblanc101** [comment]
@beholdr Yes it work, but shouldn't my exemple also work ?

**Comment by beholdr** [comment]
@mrleblanc101 I did try your example:

```
{
    mask: ['1 (###) ###-####', '(###) ###-####'],
    tokens: {
        1: { pattern: /[1]/ },
    },
}
```

and it works:
`14181231234` shows as `1 (418) 123-1234`
`4181231234` shows as `(418) 123-1234`

**Comment by mrleblanc101** [comment]
@beholdr The end result work, but as you type, it's confusing because it wont show the correct mask.
Exemple: `1418` will show as `(141) 8` instead of `1 (418)` because it use this mask `(###) ###-####` instead of matching this mask `1 (###) ###-####`

**Comment by mrleblanc101** [comment]
Here is a codesandbox for this issue too: https://codesandbox.io/s/hopeful-cerf-ieur4s?file=/src/App.vue
