### ISSUE TITLE
SSR Issue

### ISSUE THREAD

**Issue by mrleblanc101** [beholdr/maska#136]
> require() of ES Module /Users/sleblanc/www/showbizz/frontend/node_modules/maska/dist/maska.umd.js from /Users/sleblanc/www/showbizz/frontend/node_modules/vue-server-renderer/build.dev.js not supported. maska.umd.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.

**Comment by mrleblanc101** [comment]
Not sure if it should work in the Server-side in Nuxt 2.
But I loaded the directive on the client-side only and it works now:

```
// nuxt.config.js 

export default {
    plugins: [
        { src: '@/plugins/maska.js', mode: 'client' },
    ],
};
```

**Comment by Mad-Head** [comment]
same problem
