### ISSUE TITLE
No way to set initial value in Vue

### ISSUE THREAD

**Issue by jiblett1000** [beholdr/maska#138]
### Describe the bug

Hello. So, I'm currently using maska in conjunction with vee-validate(v4). Up until the maska 2.1.7 update, I was able to get a working solution to set an initial value for my inputs but it required using `:value` as well as the vmaska directive. However, if I'm not mistaken, the directive sets the input value (or listens to it) and so syncing the value separately caused some issues. 

Anyhow, I'm binding a reactive `maskObject` to the directive so that I can sync the unmasked value with vee-validate. The problem is that changing the reactive object does nothing to update the input value. Intuitively I would think that changing the unmasked value in the reactive maskObject would cause the masked value to update, but it does not. I can also not see any way of triggering maska to run after changing the unmasked value. 

Hopefully this makes sense. If it does not, I can explain further. Unless there is something I'm missing, I currently can't populate the initial value from my API in my inputs. This is perhaps more of a feature request? But, it also seems like there should be a way to do this.

**Comment by beholdr** [comment]
You can use v-model binding for setting initial value.
Anyway, please provide an online example of your code.

**Comment by jiblett1000** [comment]
Thanks @beholdr . That works. I'm still going to provide a reproduction (hopefully tomorrow) just to be sure. Could potentially be a useful addition to the docs as well...anyhow, I will post back here.

**Comment by jiblett1000** [comment]
Here's a link to my reproduction. https://github.com/jiblett1000/maska-test

Everything works totally fine. Using v-model worked like a charm so I don't have an "issue" per se. Perhaps, there could be some additional clarification in the docs? I could very well be the only one with the misunderstanding, but it seemed to me that using the reactive `maskObject` replaced the need for using v-model as it seemed a bit superfluous having the masked value in the v-model ref as well as in the `maskObject` (although the example does show using both at once).

 Or maybe adding a little blurb about setting an initial value would be nice....
 
 Anyhow, my issue is fixed so I'll close this. Thanks again for the guidance!
