### ISSUE TITLE
Show mask characters immediately, not after the next character has been entered

### ISSUE THREAD

**Issue by grouchal** [beholdr/maska#14]
Please see this GIF. We have a mask with a dot separator and the dot is only shown after we have entered the character after it. It would be great if we can see the dot once we have entered the first 2 characters and then 4 character.

![RPReplay_Final1600682337 2020-09-21 12_06_43](https://user-images.githubusercontent.com/232846/93755180-212e3800-fc03-11ea-824b-5fd43e50e313.gif)

**Comment by grouchal** [comment]
Just to understand why this is important, we use a number keypad for this input on mobile devices and as the dot is shown in the placeholder the user searches for how to enter it, but can't. Automatically showing it to the user will mean they realise they can just type 8 numbers to complete the date and that the dots come automatically.

**Comment by beholdr** [comment]
@grouchal thanks for your suggestion, I think it's really useful on mobile devices. I'll try to implement it.

**Comment by beholdr** [comment]
Implemented in 1.2.0

**Comment by grouchal** [comment]
Fantastic - thanks!
