### ISSUE TITLE
Nuxt 3 SSR error

### ISSUE THREAD

**Issue by mateusz-wyka** [beholdr/maska#145]
### Describe the bug

Nuxt version: 3.2.0
Maska version: 2.1.8

I created a plugin:
```
import { defineNuxtPlugin } from '#app';
import { vMaska } from 'maska';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.provide('vMaska', vMaska);
});
```

When I use `v-maska` directive in `<input>` I get an error.

`Cannot read properties of undefined (reading 'getSSRProps')`

![obraz](https://user-images.githubusercontent.com/89961396/231678129-e9e41bcc-47c6-41f7-b337-324f6441400d.png)

Any solutions?

**Comment by beholdr** [comment]
Can you share minimal reproduction repo?

**Comment by mateusz-wyka** [comment]
Hope it works. Remember to open `dev Logs` to see errors.

https://codesandbox.io/p/sandbox/nervous-dirac-dsrqjf

**Comment by joseehilton147** [comment]
yep i confirm this, same error

**Comment by beholdr** [comment]
Here is an example of [nuxt plugin](https://codesandbox.io/p/sandbox/vibrant-mcclintock-0emm4t) for directive.

**Comment by joseehilton147** [comment]
nice, would be good to have this on readme or a nuxt- module (i would do myself if i know how, can search but will take a time haha)

**Comment by beholdr** [comment]
I've added example of creating a Nuxt-plugin in usage section of docs.

**Comment by ruslankonev** [comment]
not work in ssr
