### ISSUE TITLE
Imported options don't work

### ISSUE THREAD

**Issue by anatolykopyl** [beholdr/maska#149]
### Description
If the options passed to `v-maska:[options]` are imported from a file, then the mask will not work. The `preProcess` and `postProcess` functions are never called.

#### Will work:
```vue
<script setup>
const options = {
  preProcess: (val: string) => val.replace(/[$,]/g, ""),
  postProcess: (val: string) => {
    if (!val) return "";

    const sub = 3 - (val.includes(".") ? val.length - val.indexOf(".") : 0);

    return Intl.NumberFormat("en-US", {
      style: "currency",
      currency: "USD"
    })
      .format(val as any)
      .slice(0, sub ? -sub : undefined);
  }
}
</script>

<template>
  <input
    v-maska:[options]
    data-maska="0.99"
    data-maska-tokens="0:\d:multiple|9:\d:optional"
    placeholder="importedOptions"
  />
</template>
```

#### Will not work:
```vue
<script setup>
import { options } from './masks'
</script>

<template>
  <input
    v-maska:[options]
    data-maska="0.99"
    data-maska-tokens="0:\d:multiple|9:\d:optional"
    placeholder="importedOptions"
  />
</template>
```

This may be an issue with Vite, because I could not reproduce with Vue CLI.

### Reproduction link
https://github.com/anatolykopyl/maska-issue-reproduction

**Comment by beholdr** [comment]
Yeah, looks like dynamic directive argument need to be assigned in the script. This works for example:

``` js
import * as masks from './masks'

const importedOptions = masks.importedOptions
```

**Comment by andreww2012** [comment]
Could that be mentioned in the docs if possible? Took me some time to figure out what's going on after I disallowed auto-imports in Nuxt 3 project (yes, it worked just fine with them enabled) and had to start importing masks explicitly.

**Comment by beholdr** [comment]
@andreww2012 I've added note with link to this issue in the docs about options usage, thank you.

**Comment by dixhuit** [comment]
Just tried this where the maska options are returned as a computed prop from a composable and it works as expected.
