### ISSUE TITLE
Typescript warning | Expected 2 arguments, but got 1

### ISSUE THREAD

**Issue by 72fcosta** [beholdr/maska#150]
Windows 10
VS Code 1.77.3
TypeScript Vue Plugin (Volar) 1.6.0
Vue, Composition API, <script setup lang="ts">

``` json
"maska": "^2.1.8"
```

``` vue
import { vMaska } from 'maska'
```

```vue
<input v-model="lorem" v-maska data-maska="##-##" />
```

v-maska:
Expected 2 arguments, but got 1.
(property) vMaska: MaskaDirective

PS: Just warning, the mask is working.

**Comment by beholdr** [comment]
Hmm, can't reproduce it with almost the same versions but on Mac. Can you create minimal repo?

**Comment by 72fcosta** [comment]
After opening this issue my editor displayed other issues. I'm going to reinstall OS and reinstall all extensions in VS Code again. Feel free to close this issue. Thanks.
