### ISSUE TITLE
data-maska-eager instant delete of first token

### ISSUE THREAD

**Issue by wvds98** [beholdr/maska#153]
Hello, I've encountered some strange behaviour you may have an opinion on.

### Description

When using the eager option, the first element of input is deleted immediatly with all static tokens  directly after it, while other static tokens have to be manually deleted. I am not entirely sure if this is inteded behaviour or not, but its different than how it worked in maska v1 and seems inconsistent.

### Reproduction

use an input with static characters and then backspace delete the input. 

<input v-maska data-maska="#. #. #. #. #." data-maska-eager>

<input v-maska data-maska="#. #. #. #. #.">

https://stackblitz.com/edit/vue-maska-s39yev?file=src%2FApp.vue

**Comment by beholdr** [comment]
Yeah, it’s kind of feature (and workaround) with eager masks.
