### ISSUE TITLE
ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by Mad-Head** [beholdr/maska#156]
I import a module in a vue component and get an error on the server side rendering context:
```bash
Error [ERR_REQUIRE_ESM]: require() of ES Module /.../node_modules/maska/dist/maska.umd.js from /.../node_modules/vue-server-renderer/build.dev.js not supported.
maska.umd.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename maska.umd.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /.../node_modules/maska/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
```
I use the custom webpack build with vue 2 ssr

**Comment by Mad-Head** [comment]
I found that the problem goes away if for example i remove `"type": "module"` from `package.json`

**Comment by beholdr** [comment]
But UMD is not CJS. What about browsers? Looks like we need third format for CJS.

**Comment by Mad-Head** [comment]
I'm not sure, but in my case it worked both in the browser and on ssr.

**Comment by beholdr** [comment]
Could you please provide minimal repo that gives such error?

**Comment by matt-meagher** [comment]
Hi @beholdr it seems this issue has gone stale, but has there been any thought to `type: module` in `package.json`? I too am getting this error in vanilla JS setup using Rollup.  Similar to Mad-Head removing `type: module` solves the issue. 
I was able to get around this by installing v `1.5.2`, but I'd love to use the newer features if possible. 

Thanks

**Comment by matt-meagher** [comment]
Thanks for getting back to me @beholdr. I actually cannot recreate outside of my storybook environment, and unfortunetly cannot share that. 
I'm going to look for alternatives.

**Comment by grantorin** [comment]
Jest in tests cannot import this module, although this library itself is tested using Jest, surrealism)

![mask](https://github.com/beholdr/maska/assets/11960014/f16c7288-afcb-4511-a48d-1dc3aa190ec7)

**Comment by beholdr** [comment]
I have just released v3-beta. Could you check if this issue still actual?

**Comment by beholdr** [comment]
Closing as inactive.
