### ISSUE TITLE
Can't import Maska in my Vue 3 TS Project

### ISSUE THREAD

**Issue by Adrek** [beholdr/maska#16]
Good day,

Please I need help. 
I have a project with Vue 3 and support for Typescript. I installed maska but can't import or Vue don't recognize it.

package.json
```
    "core-js": "^3.6.5",
    "maska": "^1.3.1", <---- Maska 1.3.1 support Vue 3
    "vue": "^3.0.3",
    "vue-class-component": "^8.0.0-0",
```

main.ts
```
import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'
import Antd from 'ant-design-vue'
import FluidWrapPage from './components/layout/FluidWrapPage.vue'
import Maska from 'maska' <<<-------- Don't recognize

import './assets/less/global.less'

const app = createApp(App)

app.component('FluidWrapPage', FluidWrapPage)

app
  .use(store)
  .use(router)
  .use(Antd)
  .use(Maska.install)
  .mount('#app')

```

The screenshot of error:
https://i.imgur.com/AJi56Cq.png

**Comment by beholdr** [comment]
Well, I have added basic TS desclarations for 1.3.2 version, please try it.
It's generated from JS files automatically, so they are generic, but should work.

And use `app.use(Maska)`, not `use(Maska.install)` for init.

**Comment by Adrek** [comment]
Thanks. It's works
