### ISSUE TITLE
doesnt accept áéí (accents)

### ISSUE THREAD

**Issue by joseehilton147** [beholdr/maska#160]
### Describe the bug

Im from Brazil, so here we have accents in a lot of words, but using maska i cant use accents, doesnt accept it.

### Reproduction link

[https://stackblitz.com/edit/vue-maska-3xo7dd?file=src%2FApp.vue](https://stackblitz.com/edit/vue-maska-3xo7dd?file=src%2FApp.vue)

**Comment by beholdr** [comment]
Because `*` token accepts only latin letters:

    '*': { pattern: /[a-zA-Z0-9]/ }

You could use custom token to accept other symbols.

**Comment by beholdr** [comment]
It’s hard to account for all cases. You can add a custom token or redefine the default token for your case.

Like this to allow any character:

    <input v-maska data-maska="**********" data-maska-tokens="*:." />

Or for given characters:

    <input v-maska data-maska="**********" data-maska-tokens="*:[a-zA-ZÀ-ÿ0-9]" />
