### ISSUE TITLE
Wrong cursor position when typing inside a string before static symbols

### ISSUE THREAD

**Issue by Draftangel** [beholdr/maska#162]
### Describe the bug

I noticed some bug in your demo with mask `##-##`. Cursor has wrong position after typed new symbol before static symbols  like`'-'` in mask template. It seems that the additional offset is not taken when calculating the new cursor position.

### Steps to reproduce

- In your demo page change mask template to `##-##`
- typed `123` // `12-3|`
- moved cursor after `2` // `12|-3`
- typed `0` // `12-|03` 
- cursor must be after `0` // `12-0|3`
- profit

### Screenshots

![image](https://github.com/beholdr/maska/assets/9318246/fdc26bf0-c8d1-47fd-ab2a-b3f0e3a55770)
![image](https://github.com/beholdr/maska/assets/9318246/a9520960-7ed5-4bbf-8ee6-d97d2a408ac4)

**Comment by Ozzmosis94** [comment]
I have same a problem

**Comment by beholdr** [comment]
Thanks for report. Should be fixed in new v3.
