### ISSUE TITLE
Wrong cursor position when typing inside a string bad character

### ISSUE THREAD

**Issue by Draftangel** [beholdr/maska#163]
...continuing #162 

### Describe the bug

I also noticed some bug in your demo with mask `####`. Cursor has wrong position after typed new symbol which doesn't match the current mask. 

### Steps to reproduce

- In your demo page change mask template to `####`
- typed `1234` // `1234|`
- moved cursor after `2` // `12|34`
- typed any letter, `s` // `123|4`
- cursor might still on dot, after `2` // `12|34`
- profit

### Screenshots

![image](https://github.com/beholdr/maska/assets/9318246/2ee90d19-03d2-4439-9911-f3a5e879ad9a)
![image](https://github.com/beholdr/maska/assets/9318246/52266e2b-958d-4038-9137-45e8a7f7dd4e)

**Comment by Ozzmosis94** [comment]
I have same a problem

**Comment by VladBrok37** [comment]
I'm also facing this issue

**Comment by jd1378** [comment]
from the docs:
> When used on input of type `number`, could have inconsistent behavior in different browsers. Use attribute `inputmode="numeric"` with `type="text"` if you need a numeric keyboard.

**Comment by beholdr** [comment]
Thanks for report. Should be fixed in new v3.
