### ISSUE TITLE
input event duplication

### ISSUE THREAD

**Issue by cyevgeniy** [beholdr/maska#168]
### Describe the bug

Maska's `input` custom event has the same name as a native `input` event; it leads to a handler function being called twice on a single change.

### Steps to reproduce

1. Add  a `v-maska` directive to an input element
2. Add an `input` event listener

### Reproduction link

https://stackblitz.com/edit/vue-maska-8fk5pv?file=src%2FApp.vue

**Comment by beholdr** [comment]
It’s not a bug, it's needed for the correct `v-model` value update. Could you propose other solution?

**Comment by desprit** [comment]
What if I'm not using v-model? I don't want two-way data flow, component propogates changes to the parent by emit event.
