### ISSUE TITLE
Double tap at the beginning of the phone mask

### ISSUE THREAD

**Issue by Akseonov** [beholdr/maska#170]
### Describe the bug

I noticed some bug in my project, but it is also present in the demo with a phone mask +1 ### ###-##-##. 
After filling in the input, delete the first 2 characters (it was +1 339 999-99-99, it became +1 9 999-99-99) and print a new character (4). Instead of one character (4) we get two (44). Playable on android.

honor 9 - EMUI 9.1.0.232

### Steps to reproduce

- In your demo page change mask template to phone (+1 ### ###-##-##)
- typed `3399999999` // `+1 339 999-99-99|`
- moved cursor after `33` // `+1 33|9 999-99-99`
- delete `33` // `+1 |9 999-99-99`
- typed `4` // `+1 44|9 999-99-99`
- one character `4` should appear, but two characters `4` appeared `+1 4|9 999-99-99`

### Reproduction link

https://drive.google.com/file/d/12Ef7VsuX_C2bIaI8ToFi1lrLiVBdp7dQ/view?usp=drive_link

**Comment by beholdr** [comment]
Sorry, can't reproduce. Tried on desktop, iphone and android.
