### ISSUE TITLE
Don't work with vuetify v-text-field

### ISSUE THREAD

**Issue by CesarBellon** [beholdr/maska#178]
### Don't work with vuetify

With the previous version (1.5.1) it works, but now nothing happens.

### Use vuetify and apply to v-text-field

Which steps do we need to take to reproduce the problem?
<v-text-field
    v-maska 
     data-maska="##,##"
    ...

**Comment by beholdr** [comment]
Was discussed previously:
- https://github.com/beholdr/maska/issues/97#issuecomment-1340614430
- https://github.com/beholdr/maska/discussions/139#discussioncomment-5171249

**Comment by hosseinghs** [comment]
I have the same issue with vuetify 3
