### ISSUE TITLE
MaxListenersExcedeedWarning when installing maska

### ISSUE THREAD

**Issue by gugurete** [beholdr/maska#185]
yarn add maska 

⠁ (node:5631) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
error An unexpected error occurred: "https://registry.yarnpkg.com/maska: ".

Environment:
Mac OS Ventura, M1 Studio

**Comment by gugurete** [comment]
"maska": "2.1.10",

**Comment by beholdr** [comment]
Can you provide full reproduction example?

**Comment by beholdr** [comment]
Close this issue now, will reopen on getting more details.
