### ISSUE TITLE
 mask reset after re-render

### ISSUE THREAD

**Issue by alloself** [beholdr/maska#192]
### Describe the bug

when hiding a component and re-rendering it, the mask in the input is reset

### Steps to reproduce 

the video shows the steps to reproduce 

1)https://codesandbox.io/s/pensive-mclaren-5gpvvf
2)https://jam.dev/c/dcb56576-db0f-4e8a-b1a3-fa5f4e14bbcd

**Comment by beholdr** [comment]
I have just released v3-beta. Could you check if this issue still actual?

**Comment by beholdr** [comment]
Closing as inactive.
