### ISSUE TITLE
How to use with input component 

### ISSUE THREAD

**Issue by Ischafak** [beholdr/maska#198]
hi its not a bug actually i just want to get recommendation from you. 

i have a input component which have label etc. 

```
<VTextInput
      v-model="form.number"
      class="mt-3"
      type="text"
      name="number"
      label="test"
      placeholder="X-X"
      small-label
      icon="smileface"
      :rules="'required|min:2|max:19'"
    />
```

something like this and i want to use maska with this when i try to give maska to this vtextinput it is not working. 
I was using vue-the-mask and it was workign with it.

do you guys have any recommedation for me that how can i use your component with this.

btw if i give maska to <input inside of this component it is working.

**Comment by beholdr** [comment]
What's this `VTextInput` component actually? If it's something like vuetify component, then probably it does not pass `data-maska` attribute to the actual input. See https://github.com/beholdr/maska/discussions/139 for more info.

**Comment by Ischafak** [comment]
it was just a component that contains <input type="text"/> with some label etc. btw i found a solution if anyone face with this problem can use something like this.


```
<VTextInput
              v-model="form.expire"
              :vmask-data="{
                'data-maska':'##/##'
              }"
              v-maska
            />
```
            
 İnside of the compenent vtextinput component

```
<input
              v-bind="{...(Object.keys(vmaskData).length !==0 ? vmaskData : {})}"
              :type="type"
              :disabled="disabled"
              @focus="$emit('focus')"
              @blur="$emit('blur')"
            >
```
