### ISSUE TITLE
Bug with dynamic mask printing unnecessary symbol

### ISSUE THREAD

**Issue by szymonc** [beholdr/maska#20]
Hi

Given we use mask  
`v-maska="['#####-####','#####']"`
after inputting 5th character it prints "-"

It does not happen with this kind of mask:
`v-maska=" ['!######', '!######-##'] `

I would expect it not to print the "-" in the first scenario.

Thanks

**Comment by beholdr** [comment]
Yes, this is a bug. Should be fixed in 1.4.1. Thanks.
