### ISSUE TITLE
Wrong cursor position when deleting/adding symbols not from the end of input 

### ISSUE THREAD

**Issue by kitmurkit2** [beholdr/maska#201]
### Describe the bug
I noticed this bug in your demo for **Money format: full via hooks**. The cursor changes its position after a new comma sign is added/removed inside of the input.

### Steps to reproduce

- In your demo page open Money format: full via hooks
- Type 1234567 // $1,234,567|
- Then move the cursor after 3 // $1,23|4,567
- Press backspace one time // $124|,567
- The cursor changed its position and now will be after 4
- Now after pressing backspace one more time 4 will be deleted // $12|,567
 
#### Actual result:
- 3 and 4 were deleted

#### Expected result:
- 2 and 3 should be deleted
- The cursor must not change its position

### Screenshots
![image](https://github.com/beholdr/maska/assets/36011861/79d928dc-bc4a-42da-981b-d8bad484639c)
![image](https://github.com/beholdr/maska/assets/36011861/c8d0b2ec-bf02-4c26-80ac-e13739932e99)
![image](https://github.com/beholdr/maska/assets/36011861/f198d476-baee-4330-b3ce-94e5a73c4151)

**Comment by Asjad-Ali** [comment]
Also, it does not opt-in the direction you specified by default

**Comment by beholdr** [comment]
Thanks for report. Should be fixed in new v3.
