### ISSUE TITLE
Cannot use dynamic mask

### ISSUE THREAD

**Issue by echjordan0** [beholdr/maska#205]
### Describe the bug

When using an array or function for the mask it does not work as expected.
With an array mask `:mask="['#####', '#####-####']"` I am able to enter two characters and then nothing happens (no errors).
![Screenshot 2024-03-05 at 4 55 34 PM](https://github.com/beholdr/maska/assets/103529370/106a75c6-1629-433a-9a15-2f44b11b6d0a)

With a function mask `v => v.length> 5 ? '#####-####' : '#####'` the function is displayed as text on input.
![Screenshot 2024-03-05 at 4 55 59 PM](https://github.com/beholdr/maska/assets/103529370/a0d3f65d-1c43-4df7-839d-e951396cf288)

Static mask value `mask="#####"` works fine.

Parent component
```vue
  <c-masked-text-field
    v-bind="$attrs"
    :id="id"
    :value="value"
    type="tel"
    name="zip"
    :label="label || $t('ZIP Code')"
    :mask="['#####', '#####-####']"
    :minlength="minlength"
    :maxlength="maxlength"
    :data-test="dataTest"
    :rules="localRules"
    pattern="[0-9]*"
    autocorrect="off"
    autocapitalize="none"
    :placeholder="placeholder || '12345'"
    @input="onInput"
    v-on="$listeners"
  />
```

Child component template
```vue
<template>
  <c-text-field
    v-bind="$attrs"
    v-maska="maskaValue"
    :data-maska="mask"
    :data-maska-tokens="tokens"
    :value="maskaValue.masked"
    :minlength="minlengthProxy"
    :maxlength="mask.length"
    @input="$emit('input', maskaValue.unmasked)"
  />
</template>
```

Child component JS
```js
@Component({
  directives: { maska: vMaska as DirectiveFunction },
})
export default class CMaskedTextField extends Vue {
  maskaValue: { masked: string; unmasked: string; completed: boolean } = {
    masked: '',
    unmasked: '',
    completed: false,
   };
...

 @Prop({ type: String, default: '' }) value!: string;
 @Prop([String, Array, Function]) mask!: MaskType;
...

 created(): void {
    this.maskaValue.masked = this.value;
  }
```

### Steps to reproduce

Which steps do we need to take to reproduce the problem?

### Reproduction link

Link to online sandbox with reproduction code.
You could use these as starters: [vue](https://stackblitz.com/edit/vue-maska) / [vanilla](https://stackblitz.com/edit/js-maska)

**Comment by beholdr** [comment]
Could you please provide a minimal reproduction link?

**Comment by beholdr** [comment]
Closing until reproduction link provided, sorry.
