### ISSUE TITLE
Mask options reversed does not work

### ISSUE THREAD

**Issue by douglasg14b** [beholdr/maska#208]
### Describe the bug

When using the maskoptions:

```ts
    const maskOptions = {
        mask: '9,99#',
        tokens: '9:[0-9]:repeated',
        reversed: true,
    };
```

```html
<input v-maska data-maska="9,99#" data-maska-tokens="9:[0-9]:repeated" data-maska-reversed>
<input v-maska:[maskOptions]>
```

The `reversed` is ignored when using `v-maska:[maskOptions]` but is not when using `data-maska-reversed`.

This becomes rather important with UI libs like vuetify where we _have_ to use the mask options and not the input props.

## Example:

https://github.com/beholdr/maska/assets/1400380/7b08290c-e1f2-4f4f-82e3-85802bc4cdc4

### Steps to reproduce

Same code as what's in the OP

### Reproduction link

Link to online sandbox with reproduction code.

Didn't have an account to save the repro, but copy paste from the stackblitz editor:

```vue
<template>
  <input v-maska:[options] />
  <input
    v-maska
    data-maska="9,99#"
    data-maska-tokens="9:[0-9]:repeated"
    data-maska-reversed
  />
</template>

<script>
import { vMaska } from 'maska';

export default {
  name: 'App',
  directives: {
    maska: vMaska,
  },
  data() {
    return {
      options: {
        mask: '9,99#',
        tokens: '9:[0-9]:repeated',
        reversed: true,
      },
    };
  },
};
</script>
```

**Comment by beholdr** [comment]
Problem not with `reversed` option, it's `tokens` format.
When using `tokens` option, pattern should be a valid regular expression object, not a string:

```js
const maskOptions = {
  mask: '9,99#',
  tokens: {9: {pattern:/[0-9]/, repeated: true}},
  reversed: true,
};
```
