### ISSUE TITLE
Jest error

### ISSUE THREAD

**Issue by PhillipeCosta** [beholdr/maska#210]
### Discussed in https://github.com/beholdr/maska/discussions/209

<div type='discussions-op-text'>

<sup>Originally posted by **PhillipeCosta** March 26, 2024</sup>
i has this error on Jest 
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     } else
|       s.tokens = R;
>     Array.isArray(s.mask) && (s.mask.length > 1 ? s.mask = [...s.mask].sort((e, a) => e.length - a.length) : s.mask = s.mask[0] ?? ""), s.mask === "" && (s.mask = null), this.opts = s;
|   }
|   masked(t) {

i use the last version of jest, and babel processor</div>

**Comment by beholdr** [comment]
Reproduction link?

**Comment by PhillipeCosta** [comment]
i use nuxt 2 and vue 2 

when i use 'yarn test -u' this error show up


![Captura de tela 2024-03-26 111040](https://github.com/beholdr/maska/assets/11618230/97680af8-f89e-42f9-9b47-ebedbcc16f67)

**Comment by beholdr** [comment]
Sorry, can't help without reproduction link.
