### ISSUE TITLE
Not work with jest 

### ISSUE THREAD

**Issue by PhillipeCosta** [beholdr/maska#211]
### Describe the bug

When i white the 'yarn test -u' Jest show error with maska plugin

### Steps to reproduce

click in link below and write yarn test -u

### Reproduction link

https://codesandbox.io/p/devbox/nuxt-jest-test-hqwlk3

**Comment by beholdr** [comment]
Sorry for delay. I'm currently working on a new major version which should resolve this issue.

**Comment by beholdr** [comment]
I have just released v3-beta. Could you check if this issue still actual?

**Comment by beholdr** [comment]
Closing as inactive.
