### ISSUE TITLE
Docs are blank

### ISSUE THREAD

**Issue by manniL** [beholdr/maska#217]
The docs at https://beholdr.github.io/maska/ are a blank white page (chrome and FF) for me

<img width="1720" alt="image" src="https://github.com/beholdr/maska/assets/640208/c5149766-53e3-48c8-bfe8-050958f1f268">

Workaround: Use [this archive.org link](https://web.archive.org/web/20240325113406/https://beholdr.github.io/maska/#/)

**Comment by beholdr** [comment]
Looks like temp issue with jsdelivr.net, now docs are working.
