### ISSUE TITLE
problems using maskRawValue

### ISSUE THREAD

**Issue by JaconsMorais** [beholdr/maska#22]
Hi.

I'm facing two problems when using maskRawValue.

(1) - maskRawValue return undefined when v-maska value is null or undefined;
(2) - maskRawValue return outdated value(value BEFORE INPUT).

I'm using one approach to mask and retrieve unmasked input, every input component returns one object like: 
`{masked: 'value masked', raw: 'value unmasked'}`

My updateValue method inside input component:
```
this.$emit("update:modelValue", {
        masked: evt.target.value,
        raw: evt.target.dataset.maskRawValue || evt.target.value,
      });
```

Now, if I insert one console.log inside the updateValue method, using one input component with "#*" mask, and I type '111'. This is the output:

![image](https://user-images.githubusercontent.com/6156243/111717427-663bcb80-882e-11eb-9ffc-1ee8ed0ceaac.png)

I think the maskRawValue should return the same value as evt.target.value, but without mask.

**Comment by beholdr** [comment]
You need to use special `@maska` event to get actual `maskRawValue`.

**Comment by JaconsMorais** [comment]
Ok, worked! Thanks
