### ISSUE TITLE
unmasked value don't work in Nuxt 3 after build to production

### ISSUE THREAD

**Issue by Trixpua** [beholdr/maska#222]
### Describe the bug

In Nuxt 3 when using in development works fine, but after build to production the unmasked value don't work. I tried with v2 and also v3, same behaviour.

### Steps to reproduce

Create a simple input as in documentation, and build to production the unmasked don't work, maskedvalue works fine.

<input type="text" v-maska:unmaskedvalue.unmasked data-maska="['(##) ####-####', '(##) #####-####']" v-model="maskedvalue">

Masked value: {{ maskedvalue }}
Unmasked value: {{ unmaskedvalue }}

**Comment by beholdr** [comment]
Confirmed, will take a look. Thanks.

**Comment by beholdr** [comment]
@Trixpua can you please check new beta3 version? But take into account that now you need to use `defineExpose` for bound variable. I have updated [the docs](https://beholdr.github.io/maska/v3/#/vue?id=bind-value).

**Comment by Trixpua** [comment]
> @Trixpua can you please check new beta3 version? But take into account that now you need to use `defineExpose` for bound variable. I have updated [the docs](https://beholdr.github.io/maska/v3/#/vue?id=bind-value).

Now it is working well. Thank you for quick response and update. And congratulations for the awesome package.
