### ISSUE TITLE
MaskInputOptions is not exported

### ISSUE THREAD

**Issue by VChet** [beholdr/maska#223]
### Describe the bug

The Vue demo shows that the v-mask options are set in a variable. In v2 I found it convenient to declare its type, so I could see type errors in the options variable itself rather than in the template directive. Do you consider exposing this interface back, or should I take a different approach in v3?

### Steps to reproduce

```ts
<script setup lang="ts">
  import { vMaska, type MaskInputOptions } from "maska/vue" // error TS2459: Module 'maska/vue' declares 'MaskInputOptions' locally, but it is not exported.

  const options: MaskInputOptions = ({
    mask: "#-#",
    eager: true
  })
</script>

<template>
  <input v-maska="options">
</template>
```

**Comment by beholdr** [comment]
`MaskInputOptions` interface is exposed, but in `maska` not `maska/vue`. Because it is generic type not vue specific:

```ts
import type { MaskInputOptions } from 'maska'
```
