### ISSUE TITLE
Formatting error

### ISSUE THREAD

**Issue by leeobrum** [beholdr/maska#224]
### Describe the bug

White space activates the mask, leaving the '('

### Steps to reproduce

try to fix it by adding some validation, so it won't let you send just '('

### Reproduction link

I did this at this entry point: [vue](https://codepen.io/beholdr/pen/qBGrLjd)

```
<template>
  <div id="app">
    <input v-maska :data-maska="dPhoneMask" v-model="sPhoneMask" />
  </div>
</template>

<script>
import { ref, computed } from "vue";
const { vMaska } = Maska;

export default {
  directives: { maska: vMaska },
  setup() {
    const sPhoneMask = ref("");
    const dPhoneMask = computed(() => {
      return sPhoneMask.value.length === 14
        ? "(##) ####-####"
        : "(##) #####-####";
    });

    return {
      sPhoneMask,
      dPhoneMask
    };
  }
};
</script>
```

**Comment by beholdr** [comment]
Hmm, why do you think it's a bug? You have a placeholder element `(` which is substituted when you press any key. If you don't want such behavior and want that `(` in the mask only allow a literal parenthesis, then mark it as a token: `data-maska-tokens="(:[\(]"`

BTW, you don't need a computed property for dynamic mask. You could just pass an array in `data-mask` for same effect:

```html
<input v-maska data-maska="['(##) ####-####', '(##) #####-####']" v-model="sPhoneMask" />
```

**Comment by leeobrum** [comment]
I understand, but in this case without a function, it creates a mask that adds both things, with computed it changes the mask depending on the amount of length.
I think it's a bug because clicking on any key or space adds the first letter of the mask, it should only work when using numbers, right?
As the mask accepts numbers and not letters or spaces, that's why I thought it was a bug hahaha

**Comment by beholdr** [comment]
There are two examples, one with dynamic masks and other with parenthesis as token:
https://codepen.io/beholdr/pen/qBGVGZg

**Comment by leeobrum** [comment]
but, using data-maska-tokens="(:[\(]", the field starts only after activating the "(", but it must activate if it starts with numbers, is there any way?

**Comment by beholdr** [comment]
I've updated example with `preProcess` hook that checks first symbol.

**Comment by leeobrum** [comment]
perfect!! Thanks a lot for the help
