### ISSUE TITLE
Number format messes up fraction digits when grouping separator is a dot

### ISSUE THREAD

**Issue by mringler** [beholdr/maska#225]
### Description

Setting `options.number.locale` to a locale that uses a dot as grouping separator (i.e. `de`, which uses a format like `1.000.000,99`) causes the masked value to lose the decimal separator. So an input of `1.5` (float)  becomes `15` (masked).

### Steps to reproduce

Set `options.number.locale` to `de` and mask a float value: 
```javascript
new Mask({number: {locale: 'de', fraction: 1}}).masked('1.5') // returns 15
```

### Reproduction link

[codepen](https://codepen.io/bl1rt/pen/MWMewxK)

### Details
Looks like the number processor always starts by unmasking the input, even during masking, when input is not masked (see [number.ts](https://github.com/beholdr/maska/blob/4ca18fba652d06ec3249b8bb7024e5ffb5713a82/src/number.ts#L21)). Since unmasking removes all occurrences of the grouping separator, when input is a float and grouping separator is a dot, the decimal point will be removed. `1.5` becomes `15`.

### Suggested fix
Either do not unmask input value during masking altogether (might break backwards compatibility), or conditionally skip unmasking during masking when group separator is a dot:
```javascript
const float = (masked && group === '.') ? value : prepare(value, group, decimal)
```

**Comment by mringler** [comment]
Hey @beholdr,
thanks for getting back to me. Yes, I figured out I had to manually mask the initial value. Thank you for confirming.

Out of curiosity, can you tell me what does not work when applying the fix to the `input` element? Do you mean that it does not work when the element comes with a masked value, i.e. putting maska on `<input value="1.000,99"/>`?

**Comment by beholdr** [comment]
Yes, it does not work properly when you pass in formatted value. Like `<input value="1.000,99" />` became `1,00` in the input. Or when you have change the input value by typing: `1.000` + `0` became `1,00` instead of `10.000`

**Comment by beholdr** [comment]
I will add a note about this issue in the docs.

**Comment by iozuniga** [comment]
It does not work even with empty input values. With this work around is working fine for me:
new MaskInput(".maska-number-es", {preProcess: (val) => val.replace(/[$.]/g, "")});
