### ISSUE TITLE
Masking money value

### ISSUE THREAD

**Issue by JaconsMorais** [beholdr/maska#23]
Hi, thanks for your time building this awesome package for vue 3...

I need to mask money, but I have been facing some problems to retrieve the value.

I need to show value masked, but retrieve value as double.

Another problem is in Brazil we use " ," as floating point, not  "."

Then, this input:
150,50

need to be parsed as:
150.50

I tried using this mask: R$ #*!,##
But, when I "unmask" the input, your package returns just numbers with out any floating point, and I need to find a way to get the floating point when unmasking the input.

**Comment by beholdr** [comment]
Yes, unmasked value will return only numbers. If you need additional transform logic you could use regular expressions, something like this: `value.replace(',', '.').replace(/[^\.0-9]+/g, '')`
