### ISSUE TITLE
Trailing zeros

### ISSUE THREAD

**Issue by mdoesburg** [beholdr/maska#230]
### Describe the bug

When typing a lot of numbers eventually only zeros are appended to the input. Maybe this is an issue related to rounding or integers/floats?

### Steps to reproduce

1. Go to: https://beholdr.github.io/maska/v3/#/
2. Open the `Number mode: money (UK)` example
3. Paste `22222222222222222` into the input
4. See the following result: `£22 222 222 222 222 224`
5. Paste `222222222222222222` into the input
6. See the following result: `£222 222 222 222 222 200`
7. Continue to type `2`
8. See more zeroes appended at the end

The `Money, via hooks (pre v3 variant)` example seems to work with the above input values, but it doesn't have all the nice built-in features that the new number mask brings to the table.

You can actually reproduce this issue with an example equivalent to the  `Money, via hooks (pre v3 variant)` example, with one addition, a `parseFloat` call:

```ts
const maskOptions = reactive({
    mask: '0.99',
    tokens: {
        0: { pattern: /\d/, multiple: true },
        9: { pattern: /\d/, optional: true },
    },
    preProcess: (val: string) => val.replace(/[$,]/g, ''),
    postProcess: (val: string) => {
        if (!val) {
            return '';
        }

        const sub = 3 - (val.includes('.') ? val.length - val.indexOf('.') : 0);

        return new Intl.NumberFormat('en-US', {
            style: 'currency',
            currency: 'USD',
        })
            .format(parseFloat(val))
            .slice(0, sub ? -sub : undefined);
    },
});
```

With the `parseFloat` call in the above example you get the trailing zero issue, without is, it works, but TypeScript won't be too happy. I think it's safe to assume this issue is caused by the `parseFloat` calls in the number file: https://github.com/beholdr/maska/blob/master/src/number.ts

### Reproduction link

- https://beholdr.github.io/maska/v3/#/

**Comment by rozsazoltan** [comment]
The error is caused by exceeding the [Number.MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) limit, beyond which the resulting number becomes inaccurate.

**Comment by beholdr** [comment]
I've added info about maximum number in the [docs](https://beholdr.github.io/maska/v3/#/options)
