### ISSUE TITLE
Dynamic mask/tokens doesn't works in nuxt3

### ISSUE THREAD

**Issue by romanslonov** [beholdr/maska#232]
### Describe the bug

I need to compute mask dynamically based on props that come from parent component. But unable to do it, it just doesn't works. Also I noticed that it doesn't render input correctly, instead of placing the actual `data-maska-tokens` it renders `data-maska-tokens="[object Object]"`.

### Steps to reproduce

Place config for `data-maska`/`data-maska-tokens` in computed.

### Reproduction link

https://stackblitz.com/edit/github-zyudma-fxhq63?file=app.vue

**Comment by rozsazoltan** [comment]
Hi! I don't really understand why you're using such a configuration. You can simply forward all settings to the v-mask. It works in your code and with your version as well.

```js
const value = ref('');
const options = computed(() => ({
  mask: dataMaska.value,
  tokens: dataMaskaTokens.value,
}))
```
```html
<div>
    <input
      type="text"
      v-model="value"
      v-maska="options"
      placeholder="Enter your value"
    />
</div>
```

![image](https://github.com/user-attachments/assets/4bcc2f71-318a-48fe-be08-70c64bc5f87b)

**Comment by rozsazoltan** [comment]
> When using `data-maska-tokens`, there are two possible formats:
> - **Full form** should be a valid JSON-string (but can use both single and double quotes) with pattern in string format without delimiters
>
> ```html
> <input data-maska="Z-Z" data-maska-tokens="{ 'Z': { 'pattern': '[A-Z]' }}">
> ```
>
> Source: [Custom Tokens](https://beholdr.github.io/maska/v3/#/tokens?id=custom-tokens) - Maska Docs

Follow instructions:
```js
const dataMaskaTokens = computed((): MaskTokens => {
  if (code.value === '+380') {
    return "{ 'u': { 'pattern': '[0-9]' } }";
  }
  if (code.value === '+40') {
    return "{ 'r': { 'pattern': '[0-9]' } }";
  }
  return "{ 'f': { 'pattern': '[1-9]' }, z: { 'pattern': '[0-9]' } }";
});
```

**Comment by beholdr** [comment]
I've added info about string format of the `data-` attributes in the [docs](https://beholdr.github.io/maska/v3/#/options)
