### ISSUE TITLE
Mask for phone number does not work correctly

### ISSUE THREAD

**Issue by azamat-747** [beholdr/maska#233]
### Describe the bug

When I want to write a phone number with code 9, the mask does not react to the first number 9 (exactly 9), other numbers react as it should. There was no problem with version 2.1.10.

### Steps to reproduce

Mask: +998 (##) ###-##-##
Eager: true

Almost all Uzbek phone numbers start with 9)

### Reproduction link

[Link](https://codepen.io/nonstop98/pen/rNERPWZ)

**Comment by jboada** [comment]
Hi @azamat-747 , the reproduction link does not work.

**Comment by azamat-747** [comment]
Hi @jboada , thanks for reply, I did as you suggested.

```const { vMaska } = Maska```
I don't think it matters here.

---

```
const onMaska = (event) => {
    console.log('event.detail', event.detail);
    console.log('phone', phone.value);
    // form.phone = event.detail.unmasked;
    phone.value = event.detail.unmasked;
};
```
![Снимок экрана от 2024-09-12 20-34-01](https://github.com/user-attachments/assets/00646d22-3439-4f35-b650-19c6caece71f)

**Comment by beholdr** [comment]
This is not a bug it’s how eager mask with a hardcoded pattern works. You enter `9` and there is `9` in the hardcoded part of the pattern. It consumes `9` as part of the pattern. Same if you enter `8` or `+`. But if you enter any other digit, like `1`, it skips hardcoded part and show `1` in the dynamic part.

**Comment by nazaralynadirbek** [comment]
> This is not a bug it’s how eager mask with a hardcoded pattern works. You enter `9` and there is `9` in the hardcoded part of the pattern. It consumes `9` as part of the pattern. Same if you enter `8` or `+`. But if you enter any other digit, like `1`, it skips hardcoded part and show `1` in the dynamic part.

I do have same issue, my mask is "+7 (###) ### ## ##", and most of our phone numbers are +7777/+7705. What can I do to handle this scenario? Right now I see only 1 option - to change mask to "+# (###) ### ## ##"

**Comment by beholdr** [comment]
I’m sorry, but this is how v3 works. Hardcoded tokens consumed by input characters. This was needed to simplify internal logic.

**Comment by rozsazoltan** [comment]
By the way, I understand the problem. The user sees an empty input field and starts typing `+998`, but after typing the `9`, `+998` appears. Since they were typing quickly, they ended up entering `+998 98`. Then they realize this and delete it to `+998` and continue entering the phone number.

**Comment by beholdr** [comment]
> I do have same issue, my mask is "+7 (###) ### ## ##", and most of our phone numbers are +7777/+7705. What can I do to handle this scenario? Right now I see only 1 option - to change mask to "+# (###) ### ## ##"

If you really want to process first `7` as masked input instead of hardcoded placeholder, you can use `preProcess` hook, for example like this:

```js
{
  mask: '+7 ### ###-##-##',
  preProcess: (val) => val === '7' ? '77' : val
}
```

**Comment by beholdr** [comment]
> By the way, I understand the problem. The user sees an empty input field and starts typing `+998`, but after typing the `9`, `+998` appears. Since they were typing quickly, they ended up entering `+998 98`. Then they realize this and delete it to `+998` and continue entering the phone number.

You can turn off eager mode to handle this case.
