### ISSUE TITLE
Safari AutoFill does not trigger an input event

### ISSUE THREAD

**Issue by spektral3** [beholdr/maska#238]
### Describe the bug
Surprisingly, it seems that when autofilling in Safari, an `input` event is not fired by the browser, so the [event handler](https://github.com/beholdr/maska/blob/c6a6646b294f3a678ce10e80396a45c73d2800b0/src/input.ts#L77) is not being executed and therefore Maska doesn't do anything. Using this in combination with Vue, the input field is left empty because change detection is not being triggered.

### Steps to reproduce
- In a Safari browser, make sure that "Using information from my contacts" is on in Settings > AutoFill
- Create an input element with a mask e.g. `(0) #########` (I've only tested this for a phone related input field)
- Make sure that `MaskaInput` is being used
- Use Safari's AutoFill feature to fill in the value

This should display an input field with a pretty yellow background and no mask applied.

### Reproduction link
https://codepen.io/supra37/pen/PoMPWJd

**Comment by beholdr** [comment]
It seems a known [Safari bug](https://bugs.webkit.org/show_bug.cgi?id=164219).

Safari doesn't fire input event, but there is a custom event with `bubbles = true`. And my own custom input events has `bubbles = false`. I've add check for `bubbles` to process mask in this case. Hope this will not break anything :) You can check it in `3.0.3` version.

**Comment by spektral3** [comment]
Hey! Thanks for looking into the issue @beholdr.
I just tested out `v3.0.3` and it's working now 🥳
