### ISSUE TITLE
cannot turn off comma in mask

### ISSUE THREAD

**Issue by johnantoni** [beholdr/maska#240]
### Describe the bug

I cannot turn off the comma when setting parameters for an input with v-maska

### Steps to reproduce

on input:

`v-maska="getMask"
`

and method:

```
  get getMask(): any {
      return { 
        tokens: {
          pattern: /[0-9]/
        },
        number: {
          fraction: 0,
          unsigned: true
        }
      };
  }

```

**Comment by beholdr** [comment]
Your description is too vague.
Can you please create a reproduction sandbox and provide more detailed steps?
