### ISSUE TITLE
Setting unsigned to false as per type definition, does not work as expected

### ISSUE THREAD

**Issue by klavdijS** [beholdr/maska#251]
Thank you for your package, it is great.

### Describe the bug

When using the MaskNumber options, setting the unsigned property to the boolean value true does not work as expected.
If you do not set it, it works as expected as code only checks if the property is null, but if you set it in the options, it is not behaving as expected 

### Steps to reproduce

Set the following object for the MaskOptions:
`
const maskaOptions = {
  number: {
    locale: props.locale,
    fraction: 2,
    unsigned: false
  },
}
`

This will not allow you to use signed values in the input.
From documentation it is expected, that it should also work if you set the property to the correct boolean value. It caused me a bit of a headache :)

### Reproduction link

Quick example:
https://codepen.io/klavdijs/pen/OPLPJYO

**Comment by beholdr** [comment]
Thank you! Should be fixed in 3.0.4
