### ISSUE TITLE
Option to 'reverse' the order in which the mask applies 

### ISSUE THREAD

**Issue by timbaas** [beholdr/maska#26]
As far as I've seen the mask currently always applies from left to right on the characters.
The mask `#,###` would give `1`, then `1,0`, then `1,00` and finally `1,000` when a user enters `1000`.

I need users to input very large numbers (9+ digit ints) so for me the comma to seperate thousands is very important.
If I could reverse the interpretation it would give: `1`, then `10`, then `100`, then `1,000`. 

I can add it and create a PR if you like?

**Comment by beholdr** [comment]
Do you want to add new option to reverse mask, something like this?

    <input v-maska="{ mask: '#,###', reverse: true }">

**Comment by augustnmonteiro** [comment]
👍🏽 need this as well, very useful for things like height, weight, ...

**Comment by bayalad7** [comment]
This worked for me

**Comment by bayalad7** [comment]
This worked for me, for the reverse option 

<input v-maska="{ mask: '[ "#,###,###,###.##" , "###,###,###.##" , "##,###,###.##" , "#,###,###.##" , "###,###.##" , "##,###.##" , "#,###.##" , "###.##" , "##.##" , "#.##" ]' }">
<input v-maska="{ mask: '[ "#,###.##" , "###.##" , "##.##" , "#.##" ]' }">
...

**Comment by brokieb** [comment]
> Do you want to add new option to reverse mask, something like this?
> 
> ```
> <input v-maska="{ mask: '#,###', reverse: true }">
> ```

This will be very usefull

**Comment by danbohea** [comment]
Also need this.

**Comment by douglasjam** [comment]
another one in need, a must have for masking

**Comment by imaxsof** [comment]
+1

**Comment by 25Das** [comment]
Same

**Comment by beholdr** [comment]
Implemented in v2
