### ISSUE TITLE
Dynamic masks don't work when using escape character "!"

### ISSUE THREAD

**Issue by tripleplayj** [beholdr/maska#3]
Very happy to see that dynamic masks are now supported! However, since we want our users to be able to backspace through the mask, I've been postfixing the masks with literals that are escaped with "!". 

For example, if we were to take blood pressure as an input, a normal number would look like this: 120/80. However, possible values can be anywhere from 70/40 to 190/100. Your dynamic implementation works if the user is not able to backspace or remove the mask from the input.

However, we want the delimiter, in this case "/" to be put in by the user.

Concrete example:
mask: '["##/", "###/"]';

input: 12
yield: 12/

input: 123
yield: 12/3 -> 123/

And in this case we can not backspace the "/". If you escape it using it like this, it works better:

mask: '["##!/", "###/"]';

However, it breaks the dynamic functionality and only applies the first mask. Do you have any idea what could be done to alleviate this or what the effort would be to fix this?

Thanks for any help.

Edit: I looked into it and it looks like it might be possible to do this with the pattern flag. However, I don't think the pattern flag support multiple inputs does it? If one token could support multiple characters it could be a viable option.

**Comment by beholdr** [comment]
Yeah, I have took a look and this is not simple. It's like you want last digit before slash as optional. But when I tried to implement optional functionality before, it wasn't easy. If you don't need to limit digits you could use repeat modificator like this:

    <input data-mask='#*/#*'>

But if you want to strictly limit to 2 or 3 digits it need some work. I will look into that but can't guarantee anything.

**Comment by tripleplayj** [comment]
Yeah I thought about using it like this as you suggested:

`'#*/#*'
`
but the problem is it doesn't restrict the input then which would allow the user to put in an incorrect amount of digits. Thanks for looking into it, I appreciate it.

**Comment by Archetipo95** [comment]
I have a similar problem `v-maska="['#!X!X', '##!X', '###']"` and I'd like to show for example `1XX` or `12X` or `123`

**Comment by drakoan** [comment]
i need number 1...4095 in vue-3
it's not work 
          v-maska="{ mask: ['409F', '40EN', 'TNNN', 'INN', 'IN', 'I'],
            tokens: {
              'N': { pattern: /[0-9]/ },
              'I': { pattern: /[1-9]/ },
              'T': { pattern: /[1-3]/ },
              'E': { pattern: /[0-8]/ },
              'F': { pattern: /[0-5]/ },
          }}"

**Comment by beholdr** [comment]
With maska v2 you could use optional tokens if that what you wanted:

``` html
<input data-maska="##X/###" data-maska-tokens="X:[0-9]:optional">
```
