### ISSUE TITLE
No formatting on model changes

### ISSUE THREAD

**Issue by jonsalvas** [beholdr/maska#31]
First of all: thanks for the awesome library it helps me to get over my frustrations of integrating Cleave with vue.js :-)

One thing I noticed: when I have a text field bound to a v-model and there are other fields writing into this model, the formatting is not applied to the updated state. Are there any plans to support this in the future? And if not: is there a way to call the maska formatter by hand on a string variable directly? This would help me to apply the formatting before writing it back to the model.

**Comment by beholdr** [comment]
I’m not sure I can repoduce your situation, but you can use maska directly by importing and using `mask` function. Something like this:

    import { mask } from 'maska'
    const maskedValue = mask(value, '###')

**Comment by pedrooliveirabefore** [comment]
@beholdr reproduction https://codesandbox.io/s/naughty-https-v2xgu?file=/src/App.vue

**Comment by beholdr** [comment]
Yeah, I'm not sure you can intercept event on native input value change in this case. So I recommend to use watcher for value and apply mask function on change.

**Comment by beholdr** [comment]
Should be fixed with 1.4.4

**Comment by DiegoMDS** [comment]
Hi first of all thank you very much for your beautiful work, congratulations. I'm using Maska version 1.5.0 with Vue 3 and Typescript and changing the value of a string property doesn't update the mask. Only on first render or when typing a value in the field. Filling in the reactive property doesn't... could you help me please?
