### ISSUE TITLE
If the first character(s) is not pattern show it initialy in the input

### ISSUE THREAD

**Issue by erkage** [beholdr/maska#32]
I think it would be very useful for phone numbers with country code. It suggest to the user where to start type their phone.

For example in Hungary we commonly use 2 types of mobile format:
'+36 ## ### ####' and '06 ## ### ####'
If one of showed initialy in the input field they know that they should only type the rest 9 numbers and not thinking which format they should start with.

And i think it's not just Hungary where this is common and will be useful 🙂 .

**Comment by beholdr** [comment]
I'm not sure if this will be within the original design. You can use standard `value` attribute if you know that your phone always starts with +36 like this: `<input value="+36" v-maska="...">`
