### ISSUE TITLE
Feat Request: add a modifier to v-maska to return the unmasked value

### ISSUE THREAD

**Issue by edumudu** [beholdr/maska#33]
Its possible to add modifiers to a directive [Info here](https://br.vuejs.org/v2/guide/custom-directive.html#Argumentos-nos-Gatilhos).

Would be great if instead use `@maska` event, simply add a directive as below.

```html
<input
   v-maska.raw="(##) ####-####"
   v-model="phone"
/>
```

**Comment by beholdr** [comment]
I'm not sure if I can implement this because the element to which the mask is applied is a native input so I don't know how to separate v-model from input value. You should use separate property for that: 

    <input ... @maska="phoneRaw = $event.target.dataset.maskRawValue">
