### ISSUE TITLE
Cannot read property match of undefined in Vue 2 and Vuetify project

### ISSUE THREAD

**Issue by AndreyYolkin** [beholdr/maska#35]
Probably It's related with Vue 3 plugin compability, but the masks became broken since 1.4.3 update (1.4.4 also return this error)
![image](https://user-images.githubusercontent.com/11289484/125147629-3003be00-e135-11eb-872e-adb7805df2d0.png)

**Comment by beholdr** [comment]
I have checked with Vue 2 and 3, maska works. Can you reproduce your setup on some sandbox?

**Comment by ntgraph** [comment]
Hi, I just upgrade Vue to 1.4.3 and v-maska to 1.4.4, any view using v-maska throws error like screen from AndreyYolkin.

**Comment by AndreyYolkin** [comment]
Thx for a waiting. I dealed with this problem.

I've created a little setup: https://codesandbox.io/s/charming-feistel-71tls?file=/pages/index.vue
It only differs by Input element. 

So, When I use Vuetify, I dont't use native inputs, but vTextField component which have input element inside. And directive is attached to the wrapper, not the element. And input type matching is getting broke.

My proposal is to add tagname checking and availability to find native input inside the wrapper (Screenshot from directive.js)
![image](https://user-images.githubusercontent.com/11289484/126570103-0a78b726-9190-467d-b5bd-597a1d9b38bf.png)

After this patch my project started to work properly. Hope it'll be help to someone

**Comment by AndreyYolkin** [comment]
Of course, this patch is not booletproof at all, because querySelector can return `null`, if there are no inputs inside the element, too.  Probably it should throw an error in this case. Also I didn't checked, does your plugin supports contenteditable elements.

**Comment by beholdr** [comment]
Should be fixed in 1.4.5
