### ISSUE TITLE
Upgrade to Vue 3.1.4 + maska 1.4.4 = broken

### ISSUE THREAD

**Issue by ntgraph** [beholdr/maska#38]
Hi, same problem here.
I just upgrade Vue to 3.1.4 and v-maska to 1.4.4, any view using v-maska throws error:

Uncaught (in promise) TypeError: Cannot read property 'match' of undefined
 at n.value (maska.esm.js?795b:6)
    at h (maska.esm.js?795b:6)
    at callWithErrorHandling (runtime-core.esm-bundler.js?5c40:155)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?5c40:164)
    at invokeDirectiveHook (runtime-core.esm-bundler.js?5c40:3952)
    at Array.eval (runtime-core.esm-bundler.js?5c40:4972)
    at flushPostFlushCbs (runtime-core.esm-bundler.js?5c40:358)
    at flushJobs (runtime-core.esm-bundler.js?5c40:394)

And the application dies.

**Comment by beholdr** [comment]
Could you share sample code for reproducing?

**Comment by ntgraph** [comment]
`<el-input
										type="text"
										v-maska="'##########'"
										v-model="number"
									/>

**Comment by beholdr** [comment]
Could you show full example with import? I tried this code and it works with vue 3.1.4 and maska 1.4.4

``` vue
<template>
  <input v-maska="'##-##'">
</template>

<script>
import { maska } from 'maska'

export default {
  name: 'App',
  directives: {
    maska
  }
}
</script>

**Comment by ntgraph** [comment]
in main.js
```
import { createApp } from 'vue'
import App from './App.vue'
import Maska from 'maska';
...
app.use(store).use(router).use(i18n, VueAxios, axios).use(Maska).use(wait).mount('#app')

**Comment by beholdr** [comment]
Honestly, I don't know why you got error, because this code also works for me with mentioned versions:

``` js
import { createApp } from 'vue'
import App from './App.vue'
import Maska from 'maska'

const app = createApp(App)
app.use(Maska).mount('#app')

**Comment by ntgraph** [comment]
Hi, I retry in another project, when upgrade vue and v-maska, same problem. Thanks in advance for helping.

**Comment by leobueno82** [comment]
Same error here, using vue 2.6.14 and maska 1.4.2

**Comment by LucasBremm** [comment]
Getting same error here, using Vue 2.6.14 and maska 1.4.2

**Comment by haiarha** [comment]
https://codesandbox.io/s/maska-demo-z0ojm?file=/src/App.vue

Here is reproducing in combination with Vuetify 2.5.7
Vue 2.6.14
maska 1.4.4

There are plenty of errors in the console on each key stroke in the input component.

**Comment by beholdr** [comment]
Could you please check with 1.4.5?

**Comment by AndreyYolkin** [comment]
> Could you please check with 1.4.5?

Yes, new version is working, thanks!
