### ISSUE TITLE
RegExp into the mask

### ISSUE THREAD

**Issue by AlexKorgot** [beholdr/maska#39]
How can I substitute RegExp into the mask, for example: ^ [0-9] [0-9]? $ | ^ 100 $. I do not see such a possibility in the documentation.

**Comment by beholdr** [comment]
What do you mean by substitute RegExp? I don't get it. You want new token or what?

**Comment by AlexKorgot** [comment]
I meant something like this

`$("#example1").inputmask('Regex', { regex: "^[1-9][0-9]?$|^100$" });`

**Comment by beholdr** [comment]
Maska don’t support complex regexp patterns, but you could create new token(s) with your rules.
