### ISSUE TITLE
Reactivity-driven dynamic masking

### ISSUE THREAD

**Issue by cchooley** [beholdr/maska#4]
Hello, and thanks for contributing such a great library!

I have one question that I'm not really able to answer based on what I'm seeing in your docs. For UX concerns, I'd like to be able to apply _one_ mask to an input field based on the state of a reactive data property being read by Vue.

My use case is detecting a credit card type and applying one of two masks based on if the card is an American Express or not. Ideally, I would like to be able to do something like the following (apologies for the extremely contrived example):

**Template:**
`<input v-model="creditcard.number" maska="creditCardMask'>`

**Computed:**
```
computed : {
  creditcardMask() {
    if (this.creditcard.type === "American Express") { // card type is detected based on the value of creditcard.number
      return "#### ###### #####";
    else {
      return "#### #### #### ####";
    }
  }
}
```

Passing those two masks as described in the docs - as an array directly into the input - isn't having the desired effect, and in some cases is negatively affecting the UI.

Any help here would be greatly appreciated, and thanks again for the package!

**Comment by beholdr** [comment]
Hi, good question. Agree with you, mask should be reactive. Now it is, please check demo page with example. Glad you found my lib useful.
