### ISSUE TITLE
Mask is not applied on vue 3 on first load

### ISSUE THREAD

**Issue by hoomersinpsom** [beholdr/maska#41]
i'm using version 1.4.2, when the value is set in the model inside setup function, the mask is not applied, i need to re render the component changing the :key parameter in some parent node to force the rendering. It should apply the mask when the component is loaded :)

**Comment by fabio-smu** [comment]
+1

**Comment by beholdr** [comment]
Should be fixed in 1.4.6

**Comment by ilcasco-alejandroc** [comment]
This issue is happening to me with Vue 3.2.19 and Maska 1.5.0

**Comment by daniloribeiro00** [comment]
Still not fixed #80
