### ISSUE TITLE
Mask with optional sign not working

### ISSUE THREAD

**Issue by matejmohar** [beholdr/maska#44]
Hi, 
I think maska is great and easy plugin, but I think it is not working as I expected it to work, when I woul like to have 2 or more mask.

For example, as I understand I can have 2 masks: v-maska="['#*,##', '-#*,##']" and it should work in that way, that the user can prefix the number with minus sign or not. But whatever I press, I can not insert minus sign?
It also alows me just to insert 4 numbers, and then deletes everything. So I guess I'm doing something wrong here?

Thanks.

**Comment by beholdr** [comment]
This case requires optional tokens. I could try to add them but don't guarantee anything.

**Comment by herickbrandao** [comment]
This pattern solves the problem for me:

```js
Maska.create('.money-mask', {
	mask: '[ "JQ#.###,##","JQ.###,##","JQ##,##","JQ#,##","JQ,##" ]',
	tokens: {
		'Q': { pattern: /[1-9]/, uppercase: true },
		'J': { pattern: new RegExp('[-?]'), uppercase: true },
	},
});
```

**Comment by beholdr** [comment]
Optional tokens implemented in maska v2.
