### ISSUE TITLE
Mask monetary value dynamically

### ISSUE THREAD

**Issue by JoaoHamerski** [beholdr/maska#47]
How to mask values like

12345678.99 TO 12,345,678.99
1234.56 TO 1,234.56

I don't know how many digits the user will input, i want to put each decimal separator correctly.

I tried create a token with regex to match a number followed by a dot as separator, but it will never work since it needs a dot to match the regex i think.

I can't think a way to do it in Maska.

**Comment by beholdr** [comment]
Reverse option implemented in maska v2
