### ISSUE TITLE
extra backspace key required for deleting

### ISSUE THREAD

**Issue by firibz** [beholdr/maska#49]
We need 1 extra backspace key for any placeholder character like '-' in patterns. In a pattern like ##-# we need 3 backspace keys to remove the second # from the right instead of 2 backspace keys.

**Comment by DanProzar** [comment]
same issue

**Comment by beholdr** [comment]
This is how this lib works.

**Comment by renerlemes** [comment]
I have the same issue too. @beholdr is possible to create a maskOption to customize this erasing question?
