### ISSUE TITLE
Input gets incorrect caret position with attached reactive

### ISSUE THREAD

**Issue by onemantooo** [beholdr/maska#50]
Hi. I couldn't understand what is a reason for such behavior, but if we have any reactive which changes it's state on focus event, and for example css class binded to this reactive, when we focus our input (by click) caret goes to start of input.

If we remove css class binding(or maska directive :) ) it works fine.

Reproduction link - https://codesandbox.io/s/competent-turing-6kmb2?file=/src/javascript/components/Coupon.vue
You can view it yourself by clicking inputs on repro link.

This becomes a big problem when you want a build custom input component 
which need to support many states, i found only one way to fix it - change reactive state inside setTimeout (even nextTick won't solve the problem), but it introduces many other problems.

https://user-images.githubusercontent.com/38207071/139776307-34fb42a6-b163-4049-a26d-d003fd564b80.mov

**Comment by onemantooo** [comment]
Checked sources a bit, and it's maybe a problem with init() -> updateValue() -> fixInputSelection() in maska.js.

Also looks like you're not removing event listeners on destroy really, this code is wrong, cause you passing not a reference to already attached function, but a new anonymous function to "removeEventListener".
![image](https://user-images.githubusercontent.com/38207071/139779809-084299ba-0b64-4bad-a6a3-e7383e3dbfe6.png)
You can check it with this demo class:
`class ListenerTest {
    constructor(el) {
        this.el = el;
        this.logger = (msg) => {
            console.log(msg);
        }
        this.el.addEventListener("click", e => this.logger("clicked"));
        this.destroy = () => {
            console.log("destroying");
            this.el.removeEventListener("click", e => this.logger("clicked"));
        }
    }
}
`

**Comment by beholdr** [comment]
You right about incorect event unsubscribing. Fixed this.
But your problem has another source in the directive code. This should be fixed in 1.4.7 too. Please check.
