### ISSUE TITLE
masking function, or value preprocessing

### ISSUE THREAD

**Issue by onemantooo** [beholdr/maska#51]
Hi. Can i somehow preprocess value before masking, or maybe pass function with masking logic.
I'm trying to handle case with safari and autofilling input.

Safari autofills card expiration date input with value "12.2032" for example, and i have a mask "## / ##".
Current mask behaviour is to turn value into 12 / 20 (which is kinda logically correct), but it's wrong as value, i want to have 12 / 32, can i achieve it somehow by now?

**Comment by beholdr** [comment]
Done, thanks!
