### ISSUE TITLE
caret position on dynamic mask

### ISSUE THREAD

**Issue by webdesignberlin** [beholdr/maska#55]
I love maska. I'm not sure if this behavior is intentional or a bug. from ux point of view, the following would be the expected behavior.

Reproduction Link: https://beholdr.github.io/maska/ (dynamic mask)

**expected behavior:**
if i fill this input with one or multiple numbers, then I would expect that the cursor/caret is always at the end of the number just entered.

**current behavior:**
the cursor/caret is always at the end of the mask.

**Comment by pleqtron** [comment]
+1

**Comment by donnyv** [comment]
This helped me with another problem. I feel like this should be taken care of by the lib.
