### ISSUE TITLE
How to write mask for numbers like '123 456 789,0',  '12 345 678,9' ?

### ISSUE THREAD

**Issue by DenniLa2** [beholdr/maska#57]
subject

**Comment by hasanparasteh** [comment]
Hi @DenniLa2 you can achieve this mask with patterns. please look at the HEX color example from demo. First create a custom token - for example letter 'N' - and then assign a regex pattern like `[0-9]` to the mask. The final result should be like this: 

```
v-maska="{ mask: '### ### ###,N', tokens: { 'N': { pattern: /[0-9]/ }}}"
```

**Comment by beholdr** [comment]
With v2 maska has reversed option, maybe it’s what you need.
