### ISSUE TITLE
Feature Request: Persian or Arabic Numbers Support

### ISSUE THREAD

**Issue by hasanparasteh** [beholdr/maska#59]
The `maska` project is really simple and easy to use but it would be great to support masking the `utf-8` numbers like Persian Numbers, Arabic Numbers and etc.

As I'm writing this feature request this issue exists and when you want to type the Persian characters, it would not get any input from user/keyboard. Please review this issue and if you want any example I can create a simple `codesandbox` for better understanding the problem...

**Comment by beholdr** [comment]
Did you tried to use custom tokens for this? Something like this i think

    <input v-maska="{ mask: 'DDD', tokens: { 'D': { pattern: /[\u06F0-\u06F9]/ }}}">
