### ISSUE TITLE
Number Input still allows "e", ".", and "-" characters as the first character input

### ISSUE THREAD

**Issue by tripleplayj** [beholdr/maska#6]
Hi,

Really like the update for the 1.1.3 version and it's helped significantly! One problem still remains though. When using input type of "number" the first character typed if [e, ., -] does not trigger the beforeInput() method. It seems like since the mask is not yet inited, that the beforeInput() method is not triggered. After backspacing it and trying to put in another invalid character, it blocks it correctly. Thanks for any updates!

Edit: This behavior is existent in Chrome.

**Comment by beholdr** [comment]
Sorry for long answer, I can't reproduce this. Could you make some demo?

**Comment by tripleplayj** [comment]
Hi,

Sorry for the long response time, other things piled up on my plate. Anyway, after inspecting the difference between yours and mine implementations of maska, it turns out that I was applying maska to it's parent element which caused it to not trigger on first keystroke. Applying maska to the actual input element fixed the problem. Thanks for the help!
