### ISSUE TITLE
Unexpected behavior with "(##) 9####-####" mask

### ISSUE THREAD

**Issue by juanbelieni** [beholdr/maska#60]
I'm trying to add a mask to a phone input in Brazilian format. So I'm using `(##) 9####-####` as the mask, but the input after `(##) 9` does not accept any number other than 9:

![image](https://user-images.githubusercontent.com/29464328/147495686-6cda0466-48eb-4444-b8f0-72fe0b02ac65.png)

**Comment by rbarbosa95** [comment]
I also use it for Brazilian standard, what I did was simply pass an array with I want the mask to apply to the input

Ex:  `['(##) ####-####', '(##) #####-####']`

**Comment by jakjr** [comment]
I can confirm this. One options:
<input v-maska="{ mask: '(##) Z ####-####', tokens: { 'Z': { pattern: /[9-9]/ }}}" class="form-control" placeholder="Ex: (41) 9 91233-4567" type="text">

**Comment by beholdr** [comment]
Should be fixed with v2

**Comment by renerlemes** [comment]
@beholdr if I use the following example, the method completed return wrong

```
import { Mask } from "maska";

const mask = new Mask({ mask: ["(##) ####-####", "(##) #####-####"] });

const value = "(64) 3453-3469";

const obj = {
  value: value,
  masked: mask.masked(value),
  unmasked: mask.unmasked(value),
  isValid: mask.completed(value)
};
``` 
mask.completed it should return true, but return false.
