### ISSUE TITLE
How set max length in mask

### ISSUE THREAD

**Issue by 7rows** [beholdr/maska#61]
Hi all, how set max length mask input 
I need the word to be no longer than 30 characters
`[{
  mask: 'SX*',
  tokens: {
    X: {
      pattern: /[a-zA-Z0-9-_-]/,
      transform: (char: string) => char.toLowerCase()
    },
    S: {
      pattern: /[a-zA-Z]/,
      transform: (char: string) => char.toLowerCase()
    }
  }
}]`

**Comment by beholdr** [comment]
You could use preprocessor function to trim value, something like this:

    mask: 'SX*',
    tokens: { ... },
    preprocessor: (value: string) => value.substr(0, 30)

**Comment by 7rows** [comment]
Thanks!
