### ISSUE TITLE
Get raw value by setting prop instead by event

### ISSUE THREAD

**Issue by maico910** [beholdr/maska#68]
Maybe is better using prop to get raw value like [Quasar mask input example](https://quasar.dev/vue-components/input#example--unmasked-model), because in some cases we need to use only the raw value, but to use we need to create another variable to just get the masked value and listening for the event

![image](https://user-images.githubusercontent.com/24510745/156778492-5778f215-44d0-48d4-b2aa-eab5c9e91e14.png)

![image](https://user-images.githubusercontent.com/24510745/156779057-0a503e09-5997-49ca-9d85-940ce88842d6.png)

**Comment by mfillon** [comment]
I agree, in many cases, we just want the mask to be a visual help while typing the value. But we want to keep the raw value in the model. An additional prop would be great.

**Comment by beholdr** [comment]
Please see docs for new v2 version, it has value binding

**Comment by mfillon** [comment]
Hey @beholdr,
Thanks for the great work on this v2.
After playing around, though, I still don't see a convenient way to do it in Vue.

The way I understand will still look like :
```
<input ...
  v-model="unmaskedValue"
  v-maska
  :data-maska="this.mask" //not sure if this is needed?
  @maska="unmaskedValue = $event.detail.unmasked"
```

Or am I missing something?

**Comment by 5e** [comment]
@mfillon 
Have you found a better solution? Was facing the same issue and unsure if there's a cleaner solution

**Comment by Philword** [comment]
Omg I spent 2 hours trying to figure out how to get raw value and still 0 progress. In my input I don't use v-model, only "name" prop because of vee-validate. How to get a raw value, can I get it anyhow with just a prop?

**Comment by mfillon** [comment]
@5e Nope, maybe using `:value="unmaskedValue"` instead of `v-model` would work better in the snippet. 

@beholdr Can you tell us how you would do it with the v2? Is the snippet I provided the way to go?

**Comment by mfillon** [comment]
> If you don’t use v-model, you can use [events](https://beholdr.github.io/maska/#/?id=events) to get raw value.

@beholdr  Is there a way to do it with `v-model` while keeping the raw value?

**Comment by beholdr** [comment]
@mfillon yes, with v-model you can get a raw value as showed in the [docs](https://beholdr.github.io/maska/#/?id=usage)

**Comment by mfillon** [comment]
From the doc, I read `To get masked value you can use standard v-model directive. But if you want to access an unmasked (raw) value, you can pass a variable as v-maska directive value.`. Which implies that `v-model` only refers to the masked value, and that the `v-maska` object (which is not the model) can contain the unmasked value.

In real world app, you would have a model, let's say a `user` with a `phoneNumber` field and let's say we want to keep this model value raw but displayed with mask.

The way I see it, you'll have to keep something in sync manually anyway, either by creating a maska object assigned to `v-maska`, but then you need to watch the maska object to replace your model value with unmasked or using `@maska` event.

@beholdr  Is that correct or am I missing something?

**Comment by beholdr** [comment]
@mfillon yes, if you want to bind a `v-model` to the raw property directly, it's impossible.

**Comment by rodrigorodriguescosta** [comment]
Having the same issue here, it should have the same feature like mentioned here unmasked model, changing the model is not a good approach, usually we need to mask only visually

I'm thinking to start using quasar for masked input due this issue
https://quasar.dev/vue-components/input/#example--unmasked-model
