### ISSUE TITLE
Mask with floating numbers

### ISSUE THREAD

**Issue by labbedaine** [beholdr/maska#69]
Hello!  

Thank you very much for providing such a great library that allows us to save time.  I have a question regarding the usage of the mask.

My use case is as follow, I need to support an input that can accept:

- Single digit (#) Ex.: 8
- Two digits at most (##) Ex.: 99
- Single digit with floating (#.##) Ex.: 8.50
- Two digits at most with floating (##.##) Ex.: 24.75

I made several attempts at using an unique mask or the array to support my use case, it works well until I reload the data, the selected mask isn't applied correctly

Ex.: 8.5 becomes 85

Also the use can't provide the dot so I can't use only ##.## since it forces me to provide 2 digits before the dot.

I would love to use the tokens but so far no luck!
`v-maska="{ mask: 'Z#.##', tokens: { 'Z': { pattern: /[0-9]?/ }, 'X': { pattern: /[\.]?/ }}}"`

Some help/guidance would be much appreciated! TY

**Comment by zourtney** [comment]
Did you get this figured out?

**Comment by labbedaine** [comment]
Nope! :)

**Comment by beholdr** [comment]
With new v2.0 version you could try to set dynamic mask with a function, something like this:

``` js
new MaskInput("[data-maska]", {
  mask: (val) => {
    return val.includes('.') ? '##.##' : '##'
  }
})
```
