### ISSUE TITLE
Wrong sequence in parts of the mask

### ISSUE THREAD

**Issue by sanistaal-bbc** [beholdr/maska#73]
We have an input field defined as

`MacAddressMask: {
        mask: 'HH:HH:HH:HH:HH:HH',
        tokens: {
            'H': {
                pattern: /[0-9a-fA-F]/
            }
        }
    },`

where to the user is scanning a barcode with a Mac-Address from a piece of hardware. Normally everything is fine but sometimes the two last parts of the mac-address is switched. Should be **aa-bb-cc-dd-ee-ff** but inputs as **aa-bb-cc-dd-ff-ee**

If we scan to a notepad document it's never scanning wrong.

**Comment by beholdr** [comment]
Please try with the new version (2.0) if issues still valid.
