### ISSUE TITLE
How to use it in Nuxt 3?

### ISSUE THREAD

**Issue by Trixpua** [beholdr/maska#74]
Is possible to use it with Nuxt 3?

I tried to make a plugin, the plugin seems to load correctly, because if I duplicate te line `nuxtApp.vueApp.use(Maska)`  appears the error `[Vue warn]: Plugin has already been applied to target app.`.

`/plugins/maska.ts`

```
import Maska from 'maska'

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.use(Maska)
});
```

I tried to make the plugin with the directive instead, it also seems to load correctly because duplicant the line `nuxtApp.vueApp.directive('maska', maska)` appears the error `[Vue warn]: Directive "maska" has already been registered in target app.`.

```
import { maska } from 'maska'

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.directive('maska', maska)
});
```

But in both cases the mask don't work, look like a normal input.

**Comment by tiYusupov** [comment]
Working for me (Nuxt 3):

`plugins/maska.ts`
```
import { maska } from "maska"

export default defineNuxtPlugin(nuxtApp => {
    nuxtApp.vueApp.directive('maska', maska)
})
```
`index.vue`
```
<ClientOnly>
      <input
          type="text"
          v-maska="'#### ######'"
      >
</ClientOnly>
```
