### ISSUE TITLE
Dynamic mask to accept only numbers and '.' 

### ISSUE THREAD

**Issue by IsidroMar95** [beholdr/maska#8]
taking this example : `data-mask='["# cm", "#.# cm", "#.## cm"]'` how can i only accept numbers and dot `.` it could be this one `data-mask="#*"` but i dont kow how to add dot.
i have tried `"['#*','.']"` but it not works i´m working with vue

I do not know if this is possible with this plugin, I mean add the `.` or `0`
![20200319_102847](https://user-images.githubusercontent.com/23019968/77090396-b2122580-69cc-11ea-9d0e-05a1d722a30e.gif)

**Comment by beholdr** [comment]
If you want only numbers and dot you could use something like this `<input v-maska="'#*.##'">`
[Example](https://codesandbox.io/s/sweet-panini-9d5ow)

**Comment by IsidroMar95** [comment]
thanks, that is exactly what i was looking for
