### ISSUE TITLE
Vue 3: "Failed to resolve directive: maska"

### ISSUE THREAD

**Issue by vsirghii** [beholdr/maska#84]
Hello, 
I have installed "maska": "^1.5.0" and I have the following in my **vue 3** main.js:

```
import Maska from 'maska';
const app = createApp(App);
app.directive('maska', Maska.maska)
```

and then in a component:
`<CFormInput id="companyein" v-model="model.employerNumber" placeholder="##-#######" v-maska="'##-#######'" />`

With this setup I'm getting error "Failed to resolve directive: maska" and the component won't open.

**Comment by vsirghii** [comment]
Seems like app.directive() doesn't work. I changed it to app.use(Maska) and now everything works as expected. 
It's just a bit confusing that I use Maska as a directive (v-maska="...") but setting it as a plugin (app.use(Maska) instead of app.directive('maska', Maska.maska))
Anyways, thanks for your component, it's really helpful.

**Comment by nagisaando** [comment]
This comment helped me. Thanks a lot!

**Comment by guifarro** [comment]
The solution of @vsirghii  is valid too, but if you want to use it as directive try this; 
```javascript
import { maska } from "maska";
const app = createApp(App);
app.directive('maska',  maska )
```

**Comment by dimatall** [comment]
`import { maska as vMaska } from 'maska'`
works for Custom Element

**Comment by petsu-app** [comment]
I'm facing this error on Nuxt 3. Followed the docs to create the plugin.
