### ISSUE TITLE
Object Rest/Spread Properties

### ISSUE THREAD

**Issue by ArnaudDoubremelle** [beholdr/maska#9]
Hello when i use my app in browser edge i have an error javascript "Expected identifier, string or number" and if i click on the error i have :
`opts.tokens = mask.tokens ? { ...mask.tokens } : {}`

my babel config is
`{
useBuiltIns: 'usage',
        corejs: 3,
}`

Thanks

**Comment by beholdr** [comment]
Well, I've cheked [demo page](https://beholdr.github.io/maska/) in Edge 80.0.361.69 and it works okay. I'm not sure I can consult about babel config options.

**Comment by ArnaudDoubremelle** [comment]
It's solved, I had to update maska to v1.1.4.
