### ISSUE TITLE
Reactive mask when the value eventually becomes null

### ISSUE THREAD

**Issue by Brunnn** [beholdr/maska#94]
Is there any way to make a reactive mask to undo the mask if the value is undefined or null, i've tried to create computed/refs of a mask and pass it to my input using the v-maska, and by some time, the mask will be null. But when it happens, the mask is not changed, it stays with the old one.

```jsx
<script lang="ts" setup>
var myMask = computed(() => {
     if (condition1){
          return { mask: "#######.###" }
     }
     else {
          return undefined;
     }

})
</script>
<template>
     <input v-maska="myMask">
</template>
```
Using Vue 3 with maska v1.5.1

**Comment by beholdr** [comment]
Please check new version (2.0), should work.
