### ISSUE TITLE
v-model gives 1 length extra value of maska input

### ISSUE THREAD

**Issue by atif0075** [beholdr/maska#95]
**Describe the bug**
 _My HTML template:_
```
         <input
                type="text"
                id="cvv"
                v-model="cvv"
                placeholder="***"
                v-maska
                data-maska="####"
                class="w-full border border-light-zinc outline-none rounded-lg p-2"
              />
      <button @click="submit"  class="w-full py-3.5 rounded-lg flex-cen" >
          Pay Now
        </button>
```
_Script_

```
let cvv = ref('')
let submit = () => {
  console.log(cvv.value);
}

```
Now If i write "12345" it will so "1234" in input field but if i log the value it'll show "12345"

<img width="469" alt="Screenshot 2022-12-05 at 7 01 14 PM" src="https://user-images.githubusercontent.com/64689549/205655986-cd001291-2913-42ea-b605-34a4a0afed43.png">

**Comment by 25Das** [comment]
I ended up using the v-maska:[options] with postProcess/preProcess hook and the slice function as a workaround.

`
options: {
          mask: '####',
          postProcess: (value) => value.slice(0, 5)
        }
`

**Comment by beholdr** [comment]
Unfortunately, this is how `v-model` works: it uses `input` event, not masked value and I don’t know how I could control it. You could use value binding to get masked value:

``` html
<script setup>
import { reactive } from 'vue';
import { vMaska } from 'maska'

const cvv = reactive({})
const submit = () => console.log(cvv.masked)
</script>

<template>
  <input v-maska="cvv" data-maska="###" />
  <button @click="submit">Pay</button>
</template>
```
